In [137]:
import numpy as np
import pandas as pd 
import seaborn as sns

In [138]:
df = pd.read_csv(r"C:\Users\gopal\OneDrive\Documents\Python_development\Data processing\credit_risk_dataset.csv")

In [139]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [140]:
df.isnull().sum()

Age                  0
Income              15
Loan_Amount          0
Credit_Score         0
Employment_Years     0
Education_Level      0
Housing_Status       0
Default              0
dtype: int64

In [141]:
df_null_list = df.isnull().sum()
df_null_list

Age                  0
Income              15
Loan_Amount          0
Credit_Score         0
Employment_Years     0
Education_Level      0
Housing_Status       0
Default              0
dtype: int64

In [142]:
df_num_clm = df.select_dtypes(include =['int','float'])

In [291]:
df_numeric = df_num_clm[df_num_clm >=0]
df_numeric

     Age    Income  Loan_Amount  Credit_Score  Employment_Years  Default
0     59   52154.0        11276           823                15        0
1     49  116646.0        43663           315                 5        0
2     35   61157.0        18994           428                 8        1
3     63   52154.0        28499           408                26        0
4     28  148876.0        28040           832                 3        1
5     41   87506.0        48320           568                26        0
6     59  107487.0        21959           461                27        0
7     39   49486.0        11099           559                 1        1
8     43   24018.0        47267           401                28        0
9     31   64028.0        24576           805                 3        1
10    31   22336.0        40946           546                 0        1
11    44  149038.0        11116           836                18        0
12    56  149038.0        20563           430                25        0
13    60   52265.0        31788           652                24        0
14    44   52265.0        31928           495                 9        0
15    23   86656.0        41336           681                20        0
16    42   75180.0        14847           526                14        0
17    22   64028.0        31155           775                26        0
18    44   61157.0        19135           776                21        0
19    64   29446.0        22774           564                18        1
20    50  116809.0         6742           671                15        0
21    58   44519.0        23309           785                20        0
22    22   63872.0         5619           733                26        0
23    41  132250.0        22658           510                23        0
24    53   74917.0        39707           676                21        0
25    32  116646.0        25337           694                 3        0
26    42   71356.0        21001           749                 1        1
27    64  148876.0         5968           663                29        0
28    45   86656.0        30892           756                24        0
29    47   91907.0        30619           525                12        0
30    62   75180.0         5281           430                27        1
31    48  107487.0        32420           775                 0        0
32    36   86656.0        20360           576                16        0
33    35   76819.0        44030           455                12        0
34    64   63872.0         6058           517                 3        0
35    23   79379.0        25677           489                 6        0
36    57  117720.0        15724           716                16        0
37    27   87779.0        33404           845                 8        1
38    41  148876.0        42946           340                 3        0
39    29   63872.0        44748           606                18        0
40    59   75180.0        34856           637                 0        0
41    38  107487.0        14200           613                 9        0
42    24   43710.0        38997           374                 3        0
43    45   52265.0        30611           578                 8        0
44    34   91895.0        46235           475                12        0
45    29   87506.0        40057           572                13        0
46    46   61157.0         6239           588                 9        0
47    22  122916.0        43138           571                 5        0
48    40  116646.0         5125           365                15        0
49    48  145733.0        28857           782                 5        0
50    27   84435.0        20398           547                16        0
51    64   84484.0        11638           455                 9        1
52    28   22336.0        11570           346                17        0
53    55  103122.0         8249           753                26        0
54    34  149038.0        14110           500                21        1
55    37   52154.0        45363           423                17        1
56    56  100910.0        18605           300                 2        0
57    60   63872.0        17115           490                19        0
58    24   66197.0        44062           815                26        0
59    22  118723.0        27911           741                20        0
60    26  116809.0        43525           442                24        0
61    62   71356.0        37556           490                27        0
62    24       NaN        17595           832                14        0
63    49   91907.0         6969           526                14        0
64    38  122916.0        48753           612                 3        0
65    46   20922.0        22275           601                28        0
66    64   86656.0         9470           759                26        0
67    54   91907.0        15225           700                 8        0
68    30   52265.0        47324           692                26        0
69    56   71356.0        46974           506                25        0
70    34       NaN        47759           509                18        0
71    51  149038.0        28196           414                23        1
72    35   63872.0        45287           550                27        0
73    28  140430.0        18669           518                16        0
74    34   20922.0        42380           706                10        1
75    43  148876.0        43006           742                24        0
76    60  103122.0        20577           653                 8        0
77    41  103122.0        27473           849                 9        1
78    36   44519.0        33625           441                17        0
79    38   86656.0        20504           800                19        0
80    44   66197.0        29089           846                12        0
81    46   79201.0        41487           841                 7        0
82    45  117720.0         5302           806                 6        0
83    61   86656.0        36463           580                16        0
84    49  116809.0        49912           723                20        0
85    35  132250.0        34259           569                22        0
86    21   24018.0        47823           453                14        0
87    45  112738.0        42208           382                19        0
88    27   79379.0        35659           725                14        0
89    29   64028.0        40840           574                 0        0
90    44   39029.0        36890           583                24        0
91    21   64028.0        18598           472                13        0
92    64   25408.0        24508           626                 4        0
93    28   75180.0        47287           362                10        0
94    44   43710.0        18380           372                15        1
95    31  149038.0        31984           674                 1        0
96    37   30789.0        49633           807                 7        0
97    28  117720.0        13125           697                10        0
98    55  112738.0        41059           419                28        1
99    55   74917.0         9033           736                17        0
100   53   30789.0        42873           764                 2        0
101   25   87779.0        22087           585                29        0
102   62   84435.0        45901           564                25        0
103   59   52154.0        10704           619                 0        0
104   61   75180.0        12848           675                10        0
105   48  118723.0        26592           388                15        1
106   27   86656.0        11924           502                17        0
107   29   84484.0        32208           633                29        0
108   28   60631.0        24614           521                15        1
109   32   20922.0         5488           340                22        0
110   54   84435.0        44882           367                 9        0
111   53  112738.0        30923           813                17        0
112   43   25408.0        40941           426                 5        0
113   44   29446.0        34165           554                18        0
114   57   66197.0         6667           315                 3        0
115   55   84435.0        31213           776                26        0
116   64   29446.0         9114           361                12        0
117   60  118723.0        41321           731                23        0
118   42   84484.0        12761           567                13        0
119   47   63872.0        36116           334                 2        0
120   55   84435.0        38768           793                 9        0
121   21  112738.0        30426           768                 5        0
122   55       NaN        22772           624                 0        0
123   57  123677.0        43218           603                22        1
124   34   76819.0         8712           575                23        0
125   23  102870.0         6367           500                26        0
126   21   71356.0        45957           744                13        0
127   25  149038.0        46781           623                 7        0
128   46   45053.0        31200           334                18        0
129   34  123677.0         8726           781                13        0
130   59  102870.0        28616           779                 9        0
131   47   52154.0        32723           364                16        0
132   29   84435.0        42574           307                 8        0
133   35   49486.0        39958           600                28        0
134   35   52154.0        14108           642                 5        0
135   46  102870.0        17178           730                10        0
136   62   91324.0        40643           723                24        0
137   33   63872.0        36324           631                 6        0
138   52   45053.0        43360           737                16        0
139   59   79379.0        22824           473                27        0
140   52       NaN        13927           826                27        0
141   24  100910.0        33144           325                 0        0
142   50  149038.0        36010           705                21        0
143   57  148876.0        27443           531                 4        0
144   43   60631.0        19437           832                 8        0
145   59   24018.0        49298           849                17        1
146   35   84484.0        44778           804                23        0
147   63   84435.0        16207           478                26        0
148   49   60631.0        30537           431                20        0
149   56  102870.0        40757           754                 1        0
150   33  132250.0        17040           647                28        1
151   52  149038.0        46986           839                25        0
152   27   87506.0        27612           705                10        0
153   42       NaN        33441           375                26        0
154   48  116646.0        11471           791                27        0
155   22   52154.0        40631           493                 5        0
156   62  136553.0        48461           461                25        0
157   26   31302.0        31523           646                 7        0
158   48  123677.0        36348           660                 3        0
159   48   44519.0         6177           386                17        0
160   64   44519.0         9760           561                27        1
161   64   45053.0        37779           513                10        0
162   40   91907.0        26636           561                 4        0
163   50   39029.0        21353           582                14        0
164   31   87779.0        16556           766                27        0
165   48   71356.0        32598           679                17        0
166   45   84484.0        16563           661                 1        0
167   59  123677.0        48790           748                21        0
168   53   60631.0        13234           740                10        1
169   21  112738.0        30519           392                25        0
170   47   52154.0        31966           723                24        0
171   33  116646.0        21173           441                12        0
172   61       NaN        31987           590                 3        0
173   23   31302.0        18178           731                21        0
174   59   30789.0        44338           348                 6        0
175   26   71356.0        29596           601                28        0
176   28  116646.0        38174           489                10        1
177   47  148876.0        46974           435                21        0
178   29  122916.0         9431           703                23        0
179   57   31302.0        32764           640                 3        0
180   53  149038.0        26627           617                27        0
181   62   87779.0        44310           662                14        0
182   64   84484.0        13906           681                 0        0
183   44  148876.0        41914           532                22        0
184   35  116646.0        49814           643                 2        0
185   52   39029.0        18076           848                13        0
186   52   79201.0        42650           828                 5        0
187   44  123677.0        11012           482                17        0
188   61   30789.0        12151           340                24        0
189   32  100910.0        33211           696                 0        0
190   59  123677.0        32117           793                 5        0
191   22   91907.0        41378           632                 5        0
192   23   75180.0        47652           426                20        0
193   57   91324.0        11894           300                15        0
194   37   87506.0        18467           467                28        0
195   22  122916.0        36010           318                 4        0
196   22   20922.0        47641           631                16        0
197   48  100910.0        17289           755                 9        0
198   43   22336.0        49976           408                27        0
199   57   91895.0        48596           567                20        0
200   52   79379.0        28171           744                17        0
201   53  112738.0        39905           539                 6        0
202   21   44519.0        25829           600                 2        0
203   39  112738.0        39054           402                12        0
204   22   87779.0        49139           549                14        1
205   64   71356.0        34734           752                19        0
206   46   20922.0        12052           819                18        0
207   52   45053.0         8654           452                 2        0
208   26   91895.0        28486           473                 3        0
209   52   45053.0        23743           642                 4        0
210   24   52265.0        29489           730                 0        0
211   31   52154.0        13636           623                 3        0
212   37   79379.0        11441           719                11        0
213   58   24018.0        29611           784                27        0
214   44       NaN        47435           711                26        0
215   25  148876.0        17149           383                23        0
216   54   61157.0        39566           412                 9        0
217   26   29446.0        47368           631                22        0
218   42  116809.0        26675           677                24        1
219   31  145733.0        10495           340                20        1
220   36   24018.0        47668           404                28        0
221   53   31302.0        18673           501                25        0
222   29   71356.0        16130           749                19        1
223   26  107487.0        27668           565                23        0
224   36   29446.0        20222           509                24        0
225   49   61157.0        28669           417                12        1
226   23  122916.0        39068           676                22        0
227   40  132250.0        28253           839                13        0
228   56  102870.0        14435           383                22        0
229   39  103122.0        33552           753                 4        0
230   46   39029.0        42384           813                 3        0
231   23   43710.0        21393           686                13        0
232   39   79201.0        15617           649                 9        0
233   40  118723.0        43520           595                16        0
234   52   43710.0        14852           557                 9        0
235   27   30789.0        36401           380                25        0
236   61   25408.0        11295           567                 6        0
237   53   44519.0        40993           718                15        1
238   60  102870.0        39084           534                 0        0
239   59   91907.0        44575           610                16        0
240   38   71356.0        41451           656                20        0
241   60  123677.0        12227           512                28        0
242   21   25408.0        36910           348                 8        0
243   31   60631.0        41041           426                 5        0
244   48  149038.0        28384           522                18        0
245   45   25408.0         5145           578                12        0
246   43  100910.0        42778           707                 2        0
247   51  103122.0        21035           804                 6        0
248   50   63872.0         8040           593                21        0
249   62   24018.0        47422           576                 8        0
250   55   49486.0        31160           737                21        0
251   27  117720.0        22633           406                 4        0
252   36  136553.0        34344           719                 9        1
253   46  103122.0        22014           728                22        0
254   22  118723.0        19996           674                16        0
255   21   75180.0        46621           372                11        0
256   32   91907.0        16695           329                22        0
257   25   87506.0         7852           487                15        0
258   57   86656.0        21014           663                 2        0
259   52   52154.0        32042           750                29        0
260   29   49486.0        38755           494                24        0
261   61   39029.0        45390           455                21        0
262   55   71356.0        28711           471                 8        0
263   39  122916.0        31122           340                28        0
264   36  116809.0        14160           362                14        0
265   23   74917.0        32213           322                 4        0
266   40   79379.0        44420           659                22        0
267   44   20922.0        12421           374                12        0
268   53  145733.0        26400           417                13        0
269   44   52265.0        38537           679                19        1
270   31   66197.0        22727           589                14        0
271   28  132250.0         9358           739                15        0

In [251]:
for i in df_numeric:
    df_numeric[i] = df_numeric[i].replace(np.nan , df_numeric[i].median())
# df_numeric['Income'] = df_numeric['Income'].replace(np.nan , df_numeric['Income'].median())

In [252]:
df_cat = df.select_dtypes(include = ["object"])

In [253]:
df_cat

    Education_Level Housing_Status
0         Bachelors            Own
1               PhD            Own
2           Masters            Own
3         Bachelors           Rent
4           Masters            Own
5               PhD            Own
6           Masters            Own
7               PhD            Own
8       High School            Own
9           Masters            Own
10          Masters           Rent
11      High School            Own
12          Masters            Own
13      High School       Mortgage
14        Bachelors           Rent
15              PhD           Rent
16      High School           Rent
17          Masters           Rent
18      High School            Own
19          Masters            Own
20        Bachelors       Mortgage
21      High School       Mortgage
22        Bachelors           Rent
23              PhD       Mortgage
24          Masters       Mortgage
25          Masters           Rent
26        Bachelors           Rent
27              PhD       Mortgage
28      High School            Own
29      High School       Mortgage
30          Masters       Mortgage
31        Bachelors            Own
32        Bachelors            Own
33      High School           Rent
34              PhD           Rent
35              PhD       Mortgage
36      High School            Own
37      High School           Rent
38        Bachelors       Mortgage
39              PhD            Own
40      High School       Mortgage
41      High School           Rent
42          Masters           Rent
43      High School            Own
44      High School       Mortgage
45              PhD            Own
46        Bachelors           Rent
47              PhD           Rent
48        Bachelors       Mortgage
49          Masters       Mortgage
50      High School       Mortgage
51          Masters            Own
52        Bachelors       Mortgage
53              PhD       Mortgage
54              PhD           Rent
55          Masters           Rent
56        Bachelors       Mortgage
57          Masters       Mortgage
58          Masters           Rent
59      High School       Mortgage
60          Masters            Own
61      High School            Own
62      High School            Own
63              PhD       Mortgage
64      High School           Rent
65      High School       Mortgage
66              PhD       Mortgage
67          Masters           Rent
68        Bachelors           Rent
69        Bachelors           Rent
70        Bachelors            Own
71          Masters       Mortgage
72      High School           Rent
73        Bachelors       Mortgage
74          Masters            Own
75      High School            Own
76              PhD           Rent
77        Bachelors           Rent
78      High School       Mortgage
79        Bachelors           Rent
80        Bachelors       Mortgage
81        Bachelors           Rent
82      High School       Mortgage
83          Masters       Mortgage
84      High School       Mortgage
85        Bachelors       Mortgage
86      High School            Own
87              PhD       Mortgage
88          Masters           Rent
89      High School            Own
90              PhD            Own
91          Masters       Mortgage
92              PhD            Own
93          Masters       Mortgage
94      High School           Rent
95              PhD       Mortgage
96        Bachelors            Own
97              PhD           Rent
98          Masters       Mortgage
99      High School           Rent
100         Masters           Rent
101             PhD            Own
102             PhD           Rent
103       Bachelors            Own
104     High School           Rent
105     High School       Mortgage
106             PhD           Rent
107     High School       Mortgage
108       Bachelors       Mortgage
109         Masters           Rent
110     High School       Mortgage
111             PhD           Rent
112         Masters           Rent
113         Masters       Mortgage
114       Bachelors       Mortgage
115             PhD            Own
116     High School       Mortgage
117             PhD            Own
118         Masters       Mortgage
119             PhD           Rent
120     High School       Mortgage
121     High School           Rent
122       Bachelors           Rent
123     High School           Rent
124     High School            Own
125             PhD       Mortgage
126             PhD           Rent
127         Masters           Rent
128       Bachelors            Own
129             PhD       Mortgage
130     High School       Mortgage
131         Masters            Own
132             PhD            Own
133       Bachelors       Mortgage
134       Bachelors            Own
135         Masters       Mortgage
136         Masters       Mortgage
137         Masters           Rent
138         Masters           Rent
139         Masters       Mortgage
140     High School       Mortgage
141     High School       Mortgage
142             PhD       Mortgage
143       Bachelors       Mortgage
144     High School       Mortgage
145     High School            Own
146     High School       Mortgage
147             PhD            Own
148         Masters            Own
149             PhD       Mortgage
150       Bachelors       Mortgage
151       Bachelors            Own
152       Bachelors            Own
153       Bachelors       Mortgage
154     High School       Mortgage
155     High School            Own
156             PhD            Own
157         Masters            Own
158       Bachelors           Rent
159             PhD            Own
160     High School           Rent
161     High School       Mortgage
162         Masters       Mortgage
163         Masters            Own
164         Masters       Mortgage
165             PhD       Mortgage
166     High School       Mortgage
167     High School       Mortgage
168         Masters           Rent
169       Bachelors           Rent
170         Masters            Own
171             PhD            Own
172         Masters            Own
173         Masters       Mortgage
174             PhD       Mortgage
175         Masters           Rent
176     High School           Rent
177       Bachelors            Own
178         Masters           Rent
179             PhD           Rent
180       Bachelors           Rent
181             PhD           Rent
182       Bachelors           Rent
183       Bachelors            Own
184         Masters            Own
185     High School           Rent
186         Masters            Own
187             PhD       Mortgage
188             PhD           Rent
189       Bachelors       Mortgage
190       Bachelors            Own
191     High School            Own
192         Masters       Mortgage
193             PhD            Own
194       Bachelors           Rent
195     High School       Mortgage
196             PhD           Rent
197       Bachelors       Mortgage
198             PhD            Own
199     High School       Mortgage
200     High School       Mortgage
201             PhD           Rent
202         Masters            Own
203             PhD           Rent
204       Bachelors            Own
205         Masters           Rent
206       Bachelors       Mortgage
207             PhD           Rent
208         Masters            Own
209       Bachelors            Own
210             PhD       Mortgage
211             PhD            Own
212         Masters           Rent
213             PhD       Mortgage
214     High School            Own
215       Bachelors            Own
216       Bachelors           Rent
217             PhD           Rent
218             PhD       Mortgage
219     High School            Own
220         Masters           Rent
221             PhD       Mortgage
222             PhD            Own
223             PhD            Own
224             PhD       Mortgage
225       Bachelors       Mortgage
226             PhD           Rent
227       Bachelors            Own
228             PhD            Own
229         Masters            Own
230     High School       Mortgage
231         Masters           Rent
232             PhD            Own
233             PhD       Mortgage
234             PhD            Own
235         Masters           Rent
236             PhD            Own
237         Masters           Rent
238       Bachelors           Rent
239     High School            Own
240     High School            Own
241         Masters           Rent
242       Bachelors       Mortgage
243         Masters           Rent
244       Bachelors            Own
245             PhD            Own
246       Bachelors       Mortgage
247       Bachelors           Rent
248       Bachelors           Rent
249     High School           Rent
250       Bachelors            Own
251             PhD           Rent
252             PhD       Mortgage
253             PhD            Own
254       Bachelors            Own
255         Masters           Rent
256         Masters       Mortgage
257             PhD            Own
258     High School            Own
259         Masters           Rent
260       Bachelors           Rent
261         Masters       Mortgage
262             PhD           Rent
263     High School       Mortgage
264         Masters            Own
265         Masters       Mortgage
266             PhD       Mortgage
267     High School       Mortgage
268     High School            Own
269             PhD           Rent
270       Bachelors            Own
271         Masters           Rent
272       Bachelors       Mortgage
273         Masters       Mortgage
274         Masters       Mortgage
275       Bachelors       Mortgage
276             PhD       Mortgage
277             PhD           Rent
278         Masters           Rent
279             PhD       Mortgage
280         Masters            Own
281             PhD            Own
282         Masters       Mortgage
283             PhD           Rent
284     High School            Own
285       Bachelors            Own
286     High School            Own
287       Bachelors       Mortgage
288       Bachelors            Own
289         Masters            Own
290       Bachelors            Own
291     High School            Own
292     High School           Rent
293             PhD       Mortgage
294     High School       Mortgage
295             PhD           Rent
296       Bachelors           Rent
297     High School       Mortgage
298       Bachelors            Own
299     High School            Own
300     High School       Mortgage
301             PhD            Own
302       Bachelors           Rent
303     High School            Own
304         Masters            Own
305       Bachelors            Own
306       Bachelors       Mortgage
307       Bachelors           Rent
308             PhD            Own
309         Masters       Mortgage
310       Bachelors            Own
311     High School           Rent
312     High School            Own
313             PhD           Rent
314     High School            Own
315       Bachelors           Rent
316     High School            Own
317       Bachelors           Rent
318     High School            Own
319         Masters            Own
320             PhD       Mortgage
321             PhD       Mortgage
322         Masters           Rent
323         Masters            Own
324             PhD           Rent
325         Masters       Mortgage
326       Bachelors           Rent
327     High School           Rent
328             PhD       Mortgage
329         Masters            Own
330       Bachelors           Rent
331             PhD       Mortgage
332         Masters            Own
333             PhD       Mortgage
334         Masters           Rent
335             PhD            Own
336       Bachelors            Own
337       Bachelors       Mortgage
338     High School       Mortgage
339             PhD       Mortgage
340     High School            Own
341             PhD            Own
342         Masters           Rent
343         Masters            Own
344     High School           Rent
345             PhD       Mortgage
346     High School       Mortgage
347       Bachelors            Own
348     High School       Mortgage
349     High School       Mortgage
350         Masters            Own
351     High School           Rent
352             PhD            Own
353         Masters           Rent
354     High School            Own
355       Bachelors            Own
356     High School       Mortgage
357     High School            Own
358     High School            Own
359         Masters           Rent
360             PhD       Mortgage
361       Bachelors           Rent
362     High School           Rent
363             PhD       Mortgage
364             PhD       Mortgage
365         Masters       Mortgage
366       Bachelors            Own
367         Masters       Mortgage
368             PhD       Mortgage
369             PhD       Mortgage
370             PhD           Rent
371         Masters           Rent
372       Bachelors            Own
373     High School           Rent
374         Masters            Own
375             PhD           Rent
376         Masters       Mortgage
377             PhD           Rent
378     High School            Own
379     High School           Rent
380       Bachelors       Mortgage
381             PhD            Own
382       Bachelors       Mortgage
383       Bachelors       Mortgage
384     High School            Own
385         Masters       Mortgage
386         Masters       Mortgage
387       Bachelors           Rent
388     High School       Mortgage
389             PhD       Mortgage
390         Masters       Mortgage
391       Bachelors       Mortgage
392         Masters            Own
393         Masters           Rent
394             PhD       Mortgage
395     High School       Mortgage
396             PhD            Own
397     High School       Mortgage
398         Masters            Own
399       Bachelors           Rent
400             PhD           Rent
401     High School       Mortgage
402         Masters       Mortgage
403     High School       Mortgage
404     High School            Own
405     High School       Mortgage
406         Masters       Mortgage
407       Bachelors           Rent
408       Bachelors       Mortgage
409       Bachelors           Rent
410     High School       Mortgage
411         Masters           Rent
412     High School       Mortgage
413       Bachelors           Rent
414       Bachelors            Own
415         Masters           Rent
416     High School           Rent
417             PhD           Rent
418             PhD       Mortgage
419       Bachelors       Mortgage
420         Masters       Mortgage
421     High School            Own
422     High School            Own
423       Bachelors           Rent
424       Bachelors            Own
425     High School           Rent
426     High School           Rent
427       Bachelors           Rent
428     High School            Own
429             PhD       Mortgage
430       Bachelors            Own
431     High School           Rent
432       Bachelors           Rent
433         Masters            Own
434       Bachelors           Rent
435       Bachelors           Rent
436         Masters            Own
437             PhD            Own
438     High School            Own
439         Masters           Rent
440       Bachelors           Rent
441     High School       Mortgage
442         Masters       Mortgage
443     High School            Own
444     High School       Mortgage
445         Masters           Rent
446     High School       Mortgage
447             PhD           Rent
448         Masters            Own
449             PhD            Own
450       Bachelors           Rent
451     High School       Mortgage
452       Bachelors            Own
453       Bachelors            Own
454     High School       Mortgage
455         Masters       Mortgage
456     High School           Rent
457       Bachelors       Mortgage
458       Bachelors       Mortgage
459         Masters       Mortgage
460     High School           Rent
461       Bachelors           Rent
462             PhD            Own
463       Bachelors           Rent
464       Bachelors            Own
465         Masters       Mortgage
466             PhD            Own
467       Bachelors            Own
468       Bachelors       Mortgage
469             PhD            Own
470     High School           Rent
471     High School           Rent
472       Bachelors           Rent
473       Bachelors           Rent
474     High School            Own
475         Masters            Own
476             PhD       Mortgage
477             PhD            Own
478         Masters            Own
479         Masters            Own
480         Masters       Mortgage
481         Masters           Rent
482         Masters            Own
483         Masters       Mortgage
484             PhD       Mortgage
485         Masters       Mortgage
486     High School           Rent
487         Masters            Own
488         Masters       Mortgage
489             PhD           Rent
490             PhD       Mortgage
491         Masters       Mortgage
492             PhD       Mortgage
493       Bachelors       Mortgage
494             PhD       Mortgage
495             PhD           Rent
496             PhD            Own
497             PhD            Own
498     High School            Own
499     High School            Own
500     High School           Rent
501         Masters           Rent
502         Masters           Rent
503       Bachelors       Mortgage
504     High School       Mortgage
505         Masters       Mortgage
506             PhD            Own
507             PhD       Mortgage
508     High School            Own
509       Bachelors       Mortgage
510       Bachelors            Own
511             PhD       Mortgage
512       Bachelors       Mortgage
513     High School           Rent
514             PhD       Mortgage
515         Masters       Mortgage
516         Masters           Rent
517       Bachelors            Own
518             PhD           Rent
519             PhD           Rent
520         Masters            Own
521             PhD       Mortgage
522             PhD            Own
523             PhD       Mortgage
524       Bachelors       Mortgage
525             PhD            Own
526     High School           Rent
527       Bachelors            Own
528             PhD       Mortgage
529             PhD            Own
530     High School            Own
531       Bachelors       Mortgage
532         Masters           Rent
533         Masters            Own
534       Bachelors       Mortgage
535             PhD       Mortgage
536             PhD            Own
537         Masters           Rent
538         Masters            Own
539         Masters           Rent
540     High School           Rent
541         Masters           Rent
542     High School           Rent
543       Bachelors            Own
544             PhD       Mortgage
545         Masters       Mortgage
546             PhD       Mortgage
547             PhD       Mortgage
548         Masters       Mortgage
549         Masters       Mortgage
550       Bachelors            Own
551     High School           Rent
552     High School       Mortgage
553             PhD            Own
554         Masters       Mortgage
555       Bachelors       Mortgage
556       Bachelors           Rent
557       Bachelors           Rent
558       Bachelors           Rent
559       Bachelors       Mortgage
560     High School       Mortgage
561     High School       Mortgage
562     High School           Rent
563         Masters            Own
564             PhD       Mortgage
565       Bachelors       Mortgage
566         Masters       Mortgage
567       Bachelors            Own
568     High School       Mortgage
569         Masters            Own

In [254]:
df_cat.isnull().sum()

Education_Level    0
Housing_Status     0
dtype: int64

In [255]:
for i in df_cat:
    print(df_cat[i].value_counts())
    print("------------------------------------------------------------------------")

Education_Level
PhD            260
Masters        253
Bachelors      248
High School    239
Name: count, dtype: int64
------------------------------------------------------------------------
Housing_Status
Mortgage    349
Own         330
Rent        321
Name: count, dtype: int64
------------------------------------------------------------------------

In [256]:
label_encoding = ["Education_Level"]
freq_encoder = ["Housing_Status"]
freq_encoder

['Housing_Status']

In [257]:
from sklearn.preprocessing import LabelEncoder

In [258]:
for i in label_encoding:
    le = LabelEncoder()
    arr = le.fit_transform(df_cat[i])
    df_cat[i] = pd.DataFrame(arr, columns=[i])

In [259]:
for i in freq_encoder:
    s = df_cat[i].value_counts()
    df_cat[i] = df_cat[i].map(s)

In [260]:
df_concat = pd.concat([df_numeric , df_cat], axis = 1)

In [261]:
df_concat

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default,Education_Level,Housing_Status
0,59,52154.0,11276,823,15,0,0,330
1,49,116646.0,43663,315,5,0,3,330
2,35,61157.0,18994,428,8,1,2,330
3,63,52154.0,28499,408,26,0,0,321
4,28,148876.0,28040,832,3,1,2,330
5,41,87506.0,48320,568,26,0,3,330
6,59,107487.0,21959,461,27,0,2,330
7,39,49486.0,11099,559,1,1,3,330
8,43,24018.0,47267,401,28,0,1,330
9,31,64028.0,24576,805,3,1,2,330
10,31,22336.0,40946,546,0,1,2,321
11,44,149038.0,11116,836,18,0,1,330
12,56,149038.0,20563,430,25,0,2,330
13,60,52265.0,31788,652,24,0,1,349
14,44,52265.0,31928,495,9,0,0,321
15,23,86656.0,41336,681,20,0,3,321
16,42,75180.0,14847,526,14,0,1,321
17,22,64028.0,31155,775,26,0,2,321
18,44,61157.0,19135,776,21,0,1,330
19,64,29446.0,22774,564,18,1,2,330
20,50,116809.0,6742,671,15,0,0,349
21,58,44519.0,23309,785,20,0,1,349
22,22,63872.0,5619,733,26,0,0,321
23,41,132250.0,22658,510,23,0,3,349
24,53,74917.0,39707,676,21,0,2,349
25,32,116646.0,25337,694,3,0,2,321
26,42,71356.0,21001,749,1,1,0,321
27,64,148876.0,5968,663,29,0,3,349
28,45,86656.0,30892,756,24,0,1,330
29,47,91907.0,30619,525,12,0,1,349
30,62,75180.0,5281,430,27,1,2,349
31,48,107487.0,32420,775,0,0,0,330
32,36,86656.0,20360,576,16,0,0,330
33,35,76819.0,44030,455,12,0,1,321
34,64,63872.0,6058,517,3,0,3,321
35,23,79379.0,25677,489,6,0,3,349
36,57,117720.0,15724,716,16,0,1,330
37,27,87779.0,33404,845,8,1,1,321
38,41,148876.0,42946,340,3,0,0,349
39,29,63872.0,44748,606,18,0,3,330
40,59,75180.0,34856,637,0,0,1,349
41,38,107487.0,14200,613,9,0,1,321
42,24,43710.0,38997,374,3,0,2,321
43,45,52265.0,30611,578,8,0,1,330
44,34,91895.0,46235,475,12,0,1,349
45,29,87506.0,40057,572,13,0,3,330
46,46,61157.0,6239,588,9,0,0,321
47,22,122916.0,43138,571,5,0,3,321
48,40,116646.0,5125,365,15,0,0,349
49,48,145733.0,28857,782,5,0,2,349
50,27,84435.0,20398,547,16,0,1,349
51,64,84484.0,11638,455,9,1,2,330
52,28,22336.0,11570,346,17,0,0,349
53,55,103122.0,8249,753,26,0,3,349
54,34,149038.0,14110,500,21,1,3,321
55,37,52154.0,45363,423,17,1,2,321
56,56,100910.0,18605,300,2,0,0,349
57,60,63872.0,17115,490,19,0,2,349
58,24,66197.0,44062,815,26,0,2,321
59,22,118723.0,27911,741,20,0,1,349
60,26,116809.0,43525,442,24,0,2,330
61,62,71356.0,37556,490,27,0,1,330
62,24,79379.0,17595,832,14,0,1,330
63,49,91907.0,6969,526,14,0,3,349
64,38,122916.0,48753,612,3,0,1,321
65,46,20922.0,22275,601,28,0,1,349
66,64,86656.0,9470,759,26,0,3,349
67,54,91907.0,15225,700,8,0,2,321
68,30,52265.0,47324,692,26,0,0,321
69,56,71356.0,46974,506,25,0,0,321
70,34,79379.0,47759,509,18,0,0,330
71,51,149038.0,28196,414,23,1,2,349
72,35,63872.0,45287,550,27,0,1,321
73,28,140430.0,18669,518,16,0,0,349
74,34,20922.0,42380,706,10,1,2,330
75,43,148876.0,43006,742,24,0,1,330
76,60,103122.0,20577,653,8,0,3,321
77,41,103122.0,27473,849,9,1,0,321
78,36,44519.0,33625,441,17,0,1,349
79,38,86656.0,20504,800,19,0,0,321
80,44,66197.0,29089,846,12,0,0,349
81,46,79201.0,41487,841,7,0,0,321
82,45,117720.0,5302,806,6,0,1,349
83,61,86656.0,36463,580,16,0,2,349
84,49,116809.0,49912,723,20,0,1,349
85,35,132250.0,34259,569,22,0,0,349
86,21,24018.0,47823,453,14,0,1,330
87,45,112738.0,42208,382,19,0,3,349
88,27,79379.0,35659,725,14,0,2,321
89,29,64028.0,40840,574,0,0,1,330
90,44,39029.0,36890,583,24,0,3,330
91,21,64028.0,18598,472,13,0,2,349
92,64,25408.0,24508,626,4,0,3,330
93,28,75180.0,47287,362,10,0,2,349
94,44,43710.0,18380,372,15,1,1,321
95,31,149038.0,31984,674,1,0,3,349
96,37,30789.0,49633,807,7,0,0,330
97,28,117720.0,13125,697,10,0,3,321
98,55,112738.0,41059,419,28,1,2,349
99,55,74917.0,9033,736,17,0,1,321
100,53,30789.0,42873,764,2,0,2,321
101,25,87779.0,22087,585,29,0,3,330
102,62,84435.0,45901,564,25,0,3,321
103,59,52154.0,10704,619,0,0,0,330
104,61,75180.0,12848,675,10,0,1,321
105,48,118723.0,26592,388,15,1,1,349
106,27,86656.0,11924,502,17,0,3,321
107,29,84484.0,32208,633,29,0,1,349
108,28,60631.0,24614,521,15,1,0,349
109,32,20922.0,5488,340,22,0,2,321
110,54,84435.0,44882,367,9,0,1,349
111,53,112738.0,30923,813,17,0,3,321
112,43,25408.0,40941,426,5,0,2,321
113,44,29446.0,34165,554,18,0,2,349
114,57,66197.0,6667,315,3,0,0,349
115,55,84435.0,31213,776,26,0,3,330
116,64,29446.0,9114,361,12,0,1,349
117,60,118723.0,41321,731,23,0,3,330
118,42,84484.0,12761,567,13,0,2,349
119,47,63872.0,36116,334,2,0,3,321
120,55,84435.0,38768,793,9,0,1,349
121,21,112738.0,30426,768,5,0,1,321
122,55,79379.0,22772,624,0,0,0,321
123,57,123677.0,43218,603,22,1,1,321
124,34,76819.0,8712,575,23,0,1,330
125,23,102870.0,6367,500,26,0,3,349
126,21,71356.0,45957,744,13,0,3,321
127,25,149038.0,46781,623,7,0,2,321
128,46,45053.0,31200,334,18,0,0,330
129,34,123677.0,8726,781,13,0,3,349
130,59,102870.0,28616,779,9,0,1,349
131,47,52154.0,32723,364,16,0,2,330
132,29,84435.0,42574,307,8,0,3,330
133,35,49486.0,39958,600,28,0,0,349
134,35,52154.0,14108,642,5,0,0,330
135,46,102870.0,17178,730,10,0,2,349
136,62,91324.0,40643,723,24,0,2,349
137,33,63872.0,36324,631,6,0,2,321
138,52,45053.0,43360,737,16,0,2,321
139,59,79379.0,22824,473,27,0,2,349
140,52,79379.0,13927,826,27,0,1,349
141,24,100910.0,33144,325,0,0,1,349
142,50,149038.0,36010,705,21,0,3,349
143,57,148876.0,27443,531,4,0,0,349
144,43,60631.0,19437,832,8,0,1,349
145,59,24018.0,49298,849,17,1,1,330
146,35,84484.0,44778,804,23,0,1,349
147,63,84435.0,16207,478,26,0,3,330
148,49,60631.0,30537,431,20,0,2,330
149,56,102870.0,40757,754,1,0,3,349
150,33,132250.0,17040,647,28,1,0,349
151,52,149038.0,46986,839,25,0,0,330
152,27,87506.0,27612,705,10,0,0,330
153,42,79379.0,33441,375,26,0,0,349
154,48,116646.0,11471,791,27,0,1,349
155,22,52154.0,40631,493,5,0,1,330
156,62,136553.0,48461,461,25,0,3,330
157,26,31302.0,31523,646,7,0,2,330
158,48,123677.0,36348,660,3,0,0,321
159,48,44519.0,6177,386,17,0,3,330
160,64,44519.0,9760,561,27,1,1,321
161,64,45053.0,37779,513,10,0,1,349
162,40,91907.0,26636,561,4,0,2,349
163,50,39029.0,21353,582,14,0,2,330
164,31,87779.0,16556,766,27,0,2,349
165,48,71356.0,32598,679,17,0,3,349
166,45,84484.0,16563,661,1,0,1,349
167,59,123677.0,48790,748,21,0,1,349
168,53,60631.0,13234,740,10,1,2,321
169,21,112738.0,30519,392,25,0,0,321
170,47,52154.0,31966,723,24,0,2,330
171,33,116646.0,21173,441,12,0,3,330
172,61,79379.0,31987,590,3,0,2,330
173,23,31302.0,18178,731,21,0,2,349
174,59,30789.0,44338,348,6,0,3,349
175,26,71356.0,29596,601,28,0,2,321
176,28,116646.0,38174,489,10,1,1,321
177,47,148876.0,46974,435,21,0,0,330
178,29,122916.0,9431,703,23,0,2,321
179,57,31302.0,32764,640,3,0,3,321
180,53,149038.0,26627,617,27,0,0,321
181,62,87779.0,44310,662,14,0,3,321
182,64,84484.0,13906,681,0,0,0,321
183,44,148876.0,41914,532,22,0,0,330
184,35,116646.0,49814,643,2,0,2,330
185,52,39029.0,18076,848,13,0,1,321
186,52,79201.0,42650,828,5,0,2,330
187,44,123677.0,11012,482,17,0,3,349
188,61,30789.0,12151,340,24,0,3,321
189,32,100910.0,33211,696,0,0,0,349
190,59,123677.0,32117,793,5,0,0,330
191,22,91907.0,41378,632,5,0,1,330
192,23,75180.0,47652,426,20,0,2,349
193,57,91324.0,11894,300,15,0,3,330
194,37,87506.0,18467,467,28,0,0,321
195,22,122916.0,36010,318,4,0,1,349
196,22,20922.0,47641,631,16,0,3,321
197,48,100910.0,17289,755,9,0,0,349
198,43,22336.0,49976,408,27,0,3,330
199,57,91895.0,48596,567,20,0,1,349
200,52,79379.0,28171,744,17,0,1,349
201,53,112738.0,39905,539,6,0,3,321
202,21,44519.0,25829,600,2,0,2,330
203,39,112738.0,39054,402,12,0,3,321
204,22,87779.0,49139,549,14,1,0,330
205,64,71356.0,34734,752,19,0,2,321
206,46,20922.0,12052,819,18,0,0,349
207,52,45053.0,8654,452,2,0,3,321
208,26,91895.0,28486,473,3,0,2,330
209,52,45053.0,23743,642,4,0,0,330
210,24,52265.0,29489,730,0,0,3,349
211,31,52154.0,13636,623,3,0,3,330
212,37,79379.0,11441,719,11,0,2,321
213,58,24018.0,29611,784,27,0,3,349
214,44,79379.0,47435,711,26,0,1,330
215,25,148876.0,17149,383,23,0,0,330
216,54,61157.0,39566,412,9,0,0,321
217,26,29446.0,47368,631,22,0,3,321
218,42,116809.0,26675,677,24,1,3,349
219,31,145733.0,10495,340,20,1,1,330
220,36,24018.0,47668,404,28,0,2,321
221,53,31302.0,18673,501,25,0,3,349
222,29,71356.0,16130,749,19,1,3,330
223,26,107487.0,27668,565,23,0,3,330
224,36,29446.0,20222,509,24,0,3,349
225,49,61157.0,28669,417,12,1,0,349
226,23,122916.0,39068,676,22,0,3,321
227,40,132250.0,28253,839,13,0,0,330
228,56,102870.0,14435,383,22,0,3,330
229,39,103122.0,33552,753,4,0,2,330
230,46,39029.0,42384,813,3,0,1,349
231,23,43710.0,21393,686,13,0,2,321
232,39,79201.0,15617,649,9,0,3,330
233,40,118723.0,43520,595,16,0,3,349
234,52,43710.0,14852,557,9,0,3,330
235,27,30789.0,36401,380,25,0,2,321
236,61,25408.0,11295,567,6,0,3,330
237,53,44519.0,40993,718,15,1,2,321
238,60,102870.0,39084,534,0,0,0,321
239,59,91907.0,44575,610,16,0,1,330
240,38,71356.0,41451,656,20,0,1,330
241,60,123677.0,12227,512,28,0,2,321
242,21,25408.0,36910,348,8,0,0,349
243,31,60631.0,41041,426,5,0,2,321
244,48,149038.0,28384,522,18,0,0,330
245,45,25408.0,5145,578,12,0,3,330
246,43,100910.0,42778,707,2,0,0,349
247,51,103122.0,21035,804,6,0,0,321
248,50,63872.0,8040,593,21,0,0,321
249,62,24018.0,47422,576,8,0,1,321
250,55,49486.0,31160,737,21,0,0,330
251,27,117720.0,22633,406,4,0,3,321
252,36,136553.0,34344,719,9,1,3,349
253,46,103122.0,22014,728,22,0,3,330
254,22,118723.0,19996,674,16,0,0,330
255,21,75180.0,46621,372,11,0,2,321
256,32,91907.0,16695,329,22,0,2,349
257,25,87506.0,7852,487,15,0,3,330
258,57,86656.0,21014,663,2,0,1,330
259,52,52154.0,32042,750,29,0,2,321
260,29,49486.0,38755,494,24,0,0,321
261,61,39029.0,45390,455,21,0,2,349
262,55,71356.0,28711,471,8,0,3,321
263,39,122916.0,31122,340,28,0,1,349
264,36,116809.0,14160,362,14,0,2,330
265,23,74917.0,32213,322,4,0,2,349
266,40,79379.0,44420,659,22,0,3,349
267,44,20922.0,12421,374,12,0,1,349
268,53,145733.0,26400,417,13,0,1,330
269,44,52265.0,38537,679,19,1,3,321
270,31,66197.0,22727,589,14,0,0,330
271,28,132250.0,9358,739,15,0,2,321
272,56,39029.0,33482,306,22,0,0,349
273,58,25408.0,37117,495,12,0,2,349
274,60,122916.0,28164,720,16,0,2,349
275,40,117720.0,36910,492,22,0,0,349
276,55,132250.0,37496,447,7,0,3,349
277,45,107487.0,49311,501,20,0,3,321
278,55,71356.0,34371,743,1,0,2,321
279,45,145733.0,43467,718,4,0,3,349
280,49,118723.0,22625,726,5,0,2,330
281,38,20922.0,38893,778,11,0,3,330
282,38,64028.0,15793,774,17,0,2,349
283,22,22336.0,36007,425,29,0,3,321
284,55,74917.0,30766,694,21,0,1,330
285,36,64028.0,44532,624,21,0,0,330
286,61,63872.0,17323,691,0,0,1,330
287,56,39029.0,12843,739,29,0,0,349
288,53,107487.0,19210,503,16,1,0,330
289,24,49486.0,21456,785,29,0,2,330
290,53,112738.0,36367,330,10,0,0,330
291,34,44519.0,15106,687,9,0,1,330
292,41,49486.0,42957,733,18,0,1,321
293,40,25408.0,7472,675,13,1,3,349
294,28,86656.0,11704,643,25,0,1,349
295,27,20922.0,8713,742,9,0,3,321
296,23,84484.0,10051,374,14,0,0,321
297,37,91907.0,15756,454,27,0,1,349
298,53,24018.0,7475,729,18,1,0,330
299,32,75180.0,41378,662,3,0,1,330
300,42,79379.0,9255,747,1,1,1,349
301,42,149038.0,19484,533,8,0,3,330
302,50,52265.0,39503,561,9,0,0,321
303,58,149038.0,13258,424,27,0,1,330
304,58,86656.0,45747,544,10,0,2,330
305,28,52154.0,40196,841,13,0,0,330
306,47,20922.0,45194,784,6,0,0,349
307,47,116809.0,13533,421,22,0,0,321
308,54,63872.0,37581,424,14,0,3,330
309,41,116809.0,10249,848,21,0,2,349
310,50,52265.0,24201,469,18,0,0,330
311,53,84435.0,14686,423,21,0,1,321
312,48,136553.0,37007,334,14,0,1,330
313,53,63872.0,5661,386,29,0,3,321
314,25,79201.0,49843,500,27,0,1,330
315,39,39029.0,35137,668,23,0,0,321
316,24,148876.0,47828,376,7,0,1,330
317,55,30789.0,15526,358,10,0,0,321
318,37,118723.0,8374,730,28,0,1,330
319,64,61157.0,30592,799,8,0,2,330
320,48,87779.0,33982,408,14,1,3,349
321,50,52265.0,5207,577,0,0,3,349
322,49,148876.0,40433,367,29,0,2,321
323,26,29446.0,28197,368,0,0,2,330
324,55,45053.0,38400,464,18,0,3,321
325,61,79201.0,8083,788,2,0,2,349
326,57,75180.0,34328,604,9,0,0,321
327,44,25408.0,47891,664,7,0,1,321
328,49,49486.0,25103,678,14,1,3,349
329,51,75180.0,44891,642,9,0,2,330
330,55,39029.0,15754,653,0,0,0,321
331,53,103122.0,39447,715,28,0,3,349
332,41,86656.0,20901,408,17,0,2,330
333,52,24018.0,38004,796,1,1,3,349
334,43,103122.0,12446,640,18,0,2,321
335,53,103122.0,42211,682,12,0,3,330
336,23,63872.0,34301,832,21,0,0,330
337,38,25408.0,31116,599,0,0,0,349
338,45,79379.0,46323,438,1,1,1,349
339,62,117720.0,23752,658,28,0,3,349
340,51,75180.0,37376,798,15,0,1,330
341,23,63872.0,21669,684,14,1,3,330
342,60,145733.0,37916,579,12,1,2,321
343,44,117720.0,18395,782,15,0,2,330
344,52,136553.0,25421,410,16,0,1,321
345,42,79201.0,31342,438,20,0,3,349
346,43,31302.0,9895,734,28,0,1,349
347,22,60631.0,16023,808,28,0,0,330
348,47,122916.0,15699,572,6,0,1,349
349,62,43710.0,14715,398,23,0,1,349
350,22,43710.0,24169,403,25,0,2,330
351,46,149038.0,21163,513,16,0,1,321
352,37,102870.0,10782,464,6,0,3,330
353,60,132250.0,27641,819,12,0,2,321
354,53,39029.0,23792,583,4,0,1,330
355,29,107487.0,40585,816,25,0,0,330
356,63,45053.0,35682,463,16,0,1,349
357,59,122916.0,23880,363,2,0,1,330
358,49,43710.0,43067,390,6,0,1,330
359,62,84435.0,47685,416,25,0,2,321
360,46,25408.0,23073,566,16,0,3,349
361,55,44519.0,41035,439,6,0,0,321
362,45,84435.0,42174,545,20,0,1,321
363,44,148876.0,29837,694,0,0,3,349
364,33,107487.0,22826,786,16,0,3,349
365,27,91324.0,29981,775,29,1,2,349
366,56,30789.0,15382,816,16,0,0,330
367,40,45053.0,9437,483,10,0,2,349
368,21,116646.0,10435,319,24,1,3,349
369,28,22336.0,29819,823,26,0,3,349
370,36,20922.0,41875,828,28,0,3,321
371,34,25408.0,36982,446,2,0,2,321
372,32,71356.0,38328,603,14,1,0,330
373,43,122916.0,17329,527,28,0,1,321
374,35,91324.0,30169,401,20,0,2,330
375,48,74917.0,26932,716,10,0,3,321
376,54,116646.0,39594,515,25,0,2,349
377,22,117720.0,16421,706,27,0,3,321
378,52,79379.0,12629,698,15,0,1,330
379,43,117720.0,13325,798,24,0,1,321
380,42,107487.0,33495,764,21,0,0,349
381,45,140430.0,36750,381,27,0,3,330
382,42,86656.0,34619,664,8,0,0,349
383,42,66197.0,45461,462,23,0,0,349
384,62,49486.0,13264,347,23,0,1,330
385,26,86656.0,17686,810,0,0,2,349
386,35,148876.0,29226,628,28,0,2,349
387,63,123677.0,11721,415,24,0,0,321
388,57,44519.0,25609,636,21,0,1,349
389,53,91324.0,12373,446,15,0,3,349
390,28,112738.0,43675,622,8,0,2,349
391,64,25408.0,33937,742,18,0,0,349
392,64,71356.0,10656,312,11,0,2,330
393,25,86656.0,13984,793,18,1,2,321
394,59,20922.0,34984,586,21,1,3,349
395,24,118723.0,13286,413,8,0,1,349
396,26,112738.0,10901,779,6,0,3,330
397,52,100910.0,36552,321,13,0,1,349
398,50,140430.0,30709,648,28,0,2,330
399,55,112738.0,36055,619,18,0,0,321
400,60,103122.0,42685,425,18,1,3,321
401,36,149038.0,13429,576,1,0,1,349
402,33,91895.0,19716,503,8,1,2,349
403,62,116646.0,16138,493,12,0,1,349
404,50,60631.0,40298,846,14,0,1,330
405,39,71356.0,28429,585,2,0,1,349
406,37,52154.0,10772,356,10,0,2,349
407,39,79379.0,40732,602,20,0,0,321
408,48,22336.0,44905,462,13,0,0,349
409,46,102870.0,22347,318,29,0,0,321
410,57,136553.0,21920,669,24,0,1,349
411,46,79201.0,36822,563,7,0,2,321
412,43,79379.0,45108,412,17,0,1,349
413,29,145733.0,28563,787,18,0,0,321
414,32,136553.0,12967,626,15,0,0,330
415,21,25408.0,16871,841,1,1,2,321
416,21,100910.0,33763,364,7,0,1,321
417,54,22336.0,16916,591,21,0,3,321
418,52,30789.0,13734,324,5,0,3,349
419,45,79201.0,38613,848,11,0,0,349
420,60,43710.0,33179,300,14,0,2,349
421,21,49486.0,40262,848,24,0,1,330
422,36,39029.0,17677,440,7,0,1,330
423,59,31302.0,23268,487,3,0,0,321
424,25,122916.0,17330,427,14,0,0,330
425,42,75180.0,25733,500,27,1,1,321
426,49,63872.0,42947,426,19,1,1,321
427,23,86656.0,32286,556,24,0,0,321
428,32,71356.0,11610,846,16,0,1,330
429,46,43710.0,11430,493,12,0,3,349
430,36,136553.0,44922,403,17,0,0,330
431,57,140430.0,18828,834,1,0,1,321
432,42,84435.0,47913,564,12,0,0,321
433,49,87506.0,36497,683,12,1,2,330
434,34,52154.0,44256,559,21,1,0,321
435,48,118723.0,41618,713,14,0,0,321
436,25,117720.0,31526,657,19,0,2,330
437,50,76819.0,35158,374,28,0,3,330
438,25,79379.0,30032,654,26,0,1,330
439,32,87779.0,42846,487,9,0,2,321
440,36,91324.0,49936,589,28,0,0,321
441,46,49486.0,34794,344,2,1,1,349
442,46,145733.0,10448,382,18,0,2,349
443,41,43710.0,33861,422,2,0,1,330
444,59,24018.0,33141,657,21,0,1,349
445,56,79201.0,14074,827,13,0,2,321
446,53,145733.0,11406,365,7,0,1,349
447,50,39029.0,36823,674,26,0,3,321
448,57,102870.0,28291,461,22,0,2,330
449,43,76819.0,46568,679,29,0,3,330
450,30,76819.0,37003,657,3,0,0,321
451,25,79379.0,39406,487,26,1,1,349
452,56,123677.0,28312,621,27,0,0,330
453,54,123677.0,48108,749,19,0,0,330
454,51,79201.0,6382,773,10,0,1,349
455,30,136553.0,39171,312,25,0,2,349
456,39,91907.0,46779,483,10,0,1,321
457,52,52154.0,8292,410,26,1,0,349
458,21,84435.0,46779,807,29,1,0,349
459,25,52154.0,38187,589,10,0,2,349
460,24,43710.0,17411,594,1,0,1,321
461,36,91324.0,42285,750,29,0,0,321
462,44,43710.0,20422,514,16,0,3,330
463,36,148876.0,47468,326,8,0,0,321
464,22,44519.0,37371,530,27,0,0,330
465,48,102870.0,10693,620,27,0,2,349
466,52,117720.0,38535,532,1,0,3,330
467,47,136553.0,19818,736,28,0,0,330
468,40,29446.0,36238,832,23,1,0,349
469,44,61157.0,35874,702,14,0,3,330
470,32,79379.0,31715,352,15,0,1,321
471,55,102870.0,32605,612,24,0,1,321
472,53,84435.0,39317,580,3,0,0,321
473,53,31302.0,36174,330,7,0,0,321
474,63,49486.0,14956,636,8,0,1,330
475,57,100910.0,43908,482,25,1,2,330
476,32,102870.0,15837,322,25,0,3,349
477,23,60631.0,8716,843,4,0,3,330
478,21,87506.0,9481,745,15,0,2,330
479,53,79379.0,29282,373,12,0,2,330
480,60,122916.0,11548,309,29,0,2,349
481,30,117720.0,42605,783,6,1,2,321
482,63,91895.0,12758,755,25,0,2,330
483,64,79379.0,48668,459,19,0,2,349
484,49,91907.0,28177,313,16,0,3,349
485,33,140430.0,29022,477,2,0,2,349
486,32,103122.0,45761,711,4,1,1,321
487,51,140430.0,10542,352,18,1,2,330
488,22,84435.0,30476,707,11,0,2,349
489,55,30789.0,35784,321,28,0,3,321
490,43,87506.0,27740,329,26,0,3,349
491,37,107487.0,29817,559,6,0,2,349
492,46,122916.0,21052,504,27,1,3,349
493,28,122916.0,40153,358,8,0,0,349
494,49,75180.0,5671,770,27,0,3,349
495,46,74917.0,5163,765,5,0,3,321
496,30,136553.0,46424,311,28,0,3,330
497,46,91907.0,49002,589,25,0,3,330
498,54,30789.0,9795,653,16,0,1,330
499,61,116809.0,15634,374,15,0,1,330
500,27,76819.0,9798,740,22,0,1,321
501,24,39029.0,27420,540,2,0,2,321
502,31,117720.0,34300,453,20,0,2,321
503,49,112738.0,29345,395,25,0,0,349
504,56,87506.0,15749,593,3,0,1,349
505,45,116646.0,43595,508,9,0,2,349
506,41,29446.0,30121,642,4,1,3,330
507,56,52154.0,42487,387,20,0,3,349
508,30,149038.0,33411,689,21,0,1,330
509,57,49486.0,38361,624,29,0,0,349
510,29,91907.0,26223,456,9,0,0,330
511,44,44519.0,12394,436,11,0,3,349
512,55,75180.0,19056,727,9,0,0,349
513,55,39029.0,33380,751,28,0,1,321
514,56,86656.0,31035,440,12,0,3,349
515,38,66197.0,35620,382,10,0,2,349
516,59,84435.0,24877,476,21,0,2,321
517,52,31302.0,48404,497,15,0,0,330
518,44,74917.0,35911,720,7,0,3,321
519,43,61157.0,37784,700,7,0,3,321
520,52,61157.0,8191,770,26,0,2,330
521,57,148876.0,38160,517,24,0,3,349
522,32,71356.0,30000,474,7,1,3,330
523,33,84435.0,44040,322,12,0,3,349
524,43,103122.0,8631,534,26,0,0,349
525,45,79201.0,11172,312,1,0,3,330
526,55,29446.0,47080,400,29,0,1,321
527,61,84435.0,28561,835,29,0,0,330
528,50,145733.0,29817,822,11,0,3,349
529,37,79201.0,25281,751,9,0,3,330
530,40,60631.0,33671,730,11,1,1,330
531,45,79379.0,30364,832,10,0,0,349
532,42,25408.0,46674,592,14,0,2,321
533,33,30789.0,32425,400,15,0,2,330
534,39,31302.0,33602,801,16,0,0,349
535,56,123677.0,28253,603,25,0,3,349
536,32,79201.0,28472,839,1,0,3,330
537,61,132250.0,13080,654,17,0,2,321
538,39,76819.0,12099,602,11,1,2,330
539,32,148876.0,30431,795,18,0,2,321
540,29,117720.0,36186,526,25,0,1,321
541,27,103122.0,35111,535,22,1,2,321
542,48,87506.0,44851,754,17,0,1,321
543,34,100910.0,27614,312,29,0,0,330
544,51,122916.0,31724,509,16,1,3,349
545,39,39029.0,46991,696,29,0,2,349
546,36,116809.0,9940,399,5,1,3,349
547,25,66197.0,33758,330,24,0,3,349
548,55,31302.0,41224,827,14,0,2,349
549,32,84484.0,12788,628,2,1,2,349
550,45,52154.0,33082,465,5,0,0,330
551,41,103122.0,29034,758,2,0,1,321
552,56,31302.0,40479,399,29,0,1,349
553,43,117720.0,16280,472,28,1,3,330
554,36,39029.0,23052,461,0,0,2,349
555,59,107487.0,21531,562,29,0,0,349

In [262]:
from sklearn.preprocessing import MinMaxScaler

In [263]:
ss = MinMaxScaler()

In [264]:
ss.fit(df_concat)

MinMaxScaler()

In [265]:
df_concat.describe().round(2)

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default,Education_Level,Housing_Status
count,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00
mean,42.52,82210.92,27729.32,581.05,15.16,0.14,1.52,333.74
std,12.61,36566.42,12774.84,158.59,8.59,0.35,1.13,11.75
min,21.00,20922.00,5097.00,300.00,0.00,0.00,0.00,321.00
25%,32.00,52154.00,16387.50,441.00,8.00,0.00,1.00,321.00
50%,43.00,79379.00,28483.50,582.00,15.00,0.00,2.00,330.00
75%,53.00,116646.00,38535.50,720.25,23.00,0.00,3.00,349.00
max,64.00,149038.00,49976.00,849.00,29.00,1.00,3.00,349.00

In [266]:
arr = ss.transform(df_concat).round(2)
arr

array([[0.88, 0.24, 0.14, ..., 0.  , 0.  , 0.32],
       [0.65, 0.75, 0.86, ..., 0.  , 1.  , 0.32],
       [0.33, 0.31, 0.31, ..., 1.  , 0.67, 0.32],
       ...,
       [0.3 , 0.64, 0.25, ..., 0.  , 0.67, 0.  ],
       [0.91, 0.35, 0.13, ..., 0.  , 1.  , 0.32],
       [0.91, 0.46, 0.06, ..., 0.  , 0.33, 1.  ]], shape=(1000, 8))

In [267]:
for i in df_concat:
    arr2 = pd.DataFrame(arr, columns =[df_concat.columns]).round(2)
arr2

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default,Education_Level,Housing_Status
0,0.88,0.24,0.14,0.95,0.52,0.0,0.00,0.32
1,0.65,0.75,0.86,0.03,0.17,0.0,1.00,0.32
2,0.33,0.31,0.31,0.23,0.28,1.0,0.67,0.32
3,0.98,0.24,0.52,0.20,0.90,0.0,0.00,0.00
4,0.16,1.00,0.51,0.97,0.10,1.0,0.67,0.32
5,0.47,0.52,0.96,0.49,0.90,0.0,1.00,0.32
6,0.88,0.68,0.38,0.29,0.93,0.0,0.67,0.32
7,0.42,0.22,0.13,0.47,0.03,1.0,1.00,0.32
8,0.51,0.02,0.94,0.18,0.97,0.0,0.33,0.32
9,0.23,0.34,0.43,0.92,0.10,1.0,0.67,0.32
10,0.23,0.01,0.80,0.45,0.00,1.0,0.67,0.00
11,0.53,1.00,0.13,0.98,0.62,0.0,0.33,0.32
12,0.81,1.00,0.34,0.24,0.86,0.0,0.67,0.32
13,0.91,0.24,0.59,0.64,0.83,0.0,0.33,1.00
14,0.53,0.24,0.60,0.36,0.31,0.0,0.00,0.00
15,0.05,0.51,0.81,0.69,0.69,0.0,1.00,0.00
16,0.49,0.42,0.22,0.41,0.48,0.0,0.33,0.00
17,0.02,0.34,0.58,0.87,0.90,0.0,0.67,0.00
18,0.53,0.31,0.31,0.87,0.72,0.0,0.33,0.32
19,1.00,0.07,0.39,0.48,0.62,1.0,0.67,0.32
20,0.67,0.75,0.04,0.68,0.52,0.0,0.00,1.00
21,0.86,0.18,0.41,0.88,0.69,0.0,0.33,1.00
22,0.02,0.34,0.01,0.79,0.90,0.0,0.00,0.00
23,0.47,0.87,0.39,0.38,0.79,0.0,1.00,1.00
24,0.74,0.42,0.77,0.68,0.72,0.0,0.67,1.00
25,0.26,0.75,0.45,0.72,0.10,0.0,0.67,0.00
26,0.49,0.39,0.35,0.82,0.03,1.0,0.00,0.00
27,1.00,1.00,0.02,0.66,1.00,0.0,1.00,1.00
28,0.56,0.51,0.57,0.83,0.83,0.0,0.33,0.32
29,0.60,0.55,0.57,0.41,0.41,0.0,0.33,1.00
30,0.95,0.42,0.00,0.24,0.93,1.0,0.67,1.00
31,0.63,0.68,0.61,0.87,0.00,0.0,0.00,0.32
32,0.35,0.51,0.34,0.50,0.55,0.0,0.00,0.32
33,0.33,0.44,0.87,0.28,0.41,0.0,0.33,0.00
34,1.00,0.34,0.02,0.40,0.10,0.0,1.00,0.00
35,0.05,0.46,0.46,0.34,0.21,0.0,1.00,1.00
36,0.84,0.76,0.24,0.76,0.55,0.0,0.33,0.32
37,0.14,0.52,0.63,0.99,0.28,1.0,0.33,0.00
38,0.47,1.00,0.84,0.07,0.10,0.0,0.00,1.00
39,0.19,0.34,0.88,0.56,0.62,0.0,1.00,0.32
40,0.88,0.42,0.66,0.61,0.00,0.0,0.33,1.00
41,0.40,0.68,0.20,0.57,0.31,0.0,0.33,0.00
42,0.07,0.18,0.76,0.13,0.10,0.0,0.67,0.00
43,0.56,0.24,0.57,0.51,0.28,0.0,0.33,0.32
44,0.30,0.55,0.92,0.32,0.41,0.0,0.33,1.00
45,0.19,0.52,0.78,0.50,0.45,0.0,1.00,0.32
46,0.58,0.31,0.03,0.52,0.31,0.0,0.00,0.00
47,0.02,0.80,0.85,0.49,0.17,0.0,1.00,0.00
48,0.44,0.75,0.00,0.12,0.52,0.0,0.00,1.00
49,0.63,0.97,0.53,0.88,0.17,0.0,0.67,1.00
50,0.14,0.50,0.34,0.45,0.55,0.0,0.33,1.00
51,1.00,0.50,0.15,0.28,0.31,1.0,0.67,0.32
52,0.16,0.01,0.14,0.08,0.59,0.0,0.00,1.00
53,0.79,0.64,0.07,0.83,0.90,0.0,1.00,1.00
54,0.30,1.00,0.20,0.36,0.72,1.0,1.00,0.00
55,0.37,0.24,0.90,0.22,0.59,1.0,0.67,0.00
56,0.81,0.62,0.30,0.00,0.07,0.0,0.00,1.00
57,0.91,0.34,0.27,0.35,0.66,0.0,0.67,1.00
58,0.07,0.35,0.87,0.94,0.90,0.0,0.67,0.00
59,0.02,0.76,0.51,0.80,0.69,0.0,0.33,1.00
60,0.12,0.75,0.86,0.26,0.83,0.0,0.67,0.32
61,0.95,0.39,0.72,0.35,0.93,0.0,0.33,0.32
62,0.07,0.46,0.28,0.97,0.48,0.0,0.33,0.32
63,0.65,0.55,0.04,0.41,0.48,0.0,1.00,1.00
64,0.40,0.80,0.97,0.57,0.10,0.0,0.33,0.00
65,0.58,0.00,0.38,0.55,0.97,0.0,0.33,1.00
66,1.00,0.51,0.10,0.84,0.90,0.0,1.00,1.00
67,0.77,0.55,0.23,0.73,0.28,0.0,0.67,0.00
68,0.21,0.24,0.94,0.71,0.90,0.0,0.00,0.00
69,0.81,0.39,0.93,0.38,0.86,0.0,0.00,0.00
70,0.30,0.46,0.95,0.38,0.62,0.0,0.00,0.32
71,0.70,1.00,0.51,0.21,0.79,1.0,0.67,1.00
72,0.33,0.34,0.90,0.46,0.93,0.0,0.33,0.00
73,0.16,0.93,0.30,0.40,0.55,0.0,0.00,1.00
74,0.30,0.00,0.83,0.74,0.34,1.0,0.67,0.32
75,0.51,1.00,0.84,0.81,0.83,0.0,0.33,0.32
76,0.91,0.64,0.34,0.64,0.28,0.0,1.00,0.00
77,0.47,0.64,0.50,1.00,0.31,1.0,0.00,0.00
78,0.35,0.18,0.64,0.26,0.59,0.0,0.33,1.00
79,0.40,0.51,0.34,0.91,0.66,0.0,0.00,0.00
80,0.53,0.35,0.53,0.99,0.41,0.0,0.00,1.00
81,0.58,0.45,0.81,0.99,0.24,0.0,0.00,0.00
82,0.56,0.76,0.00,0.92,0.21,0.0,0.33,1.00
83,0.93,0.51,0.70,0.51,0.55,0.0,0.67,1.00
84,0.65,0.75,1.00,0.77,0.69,0.0,0.33,1.00
85,0.33,0.87,0.65,0.49,0.76,0.0,0.00,1.00
86,0.00,0.02,0.95,0.28,0.48,0.0,0.33,0.32
87,0.56,0.72,0.83,0.15,0.66,0.0,1.00,1.00
88,0.14,0.46,0.68,0.77,0.48,0.0,0.67,0.00
89,0.19,0.34,0.80,0.50,0.00,0.0,0.33,0.32
90,0.53,0.14,0.71,0.52,0.83,0.0,1.00,0.32
91,0.00,0.34,0.30,0.31,0.45,0.0,0.67,1.00
92,1.00,0.04,0.43,0.59,0.14,0.0,1.00,0.32
93,0.16,0.42,0.94,0.11,0.34,0.0,0.67,1.00
94,0.53,0.18,0.30,0.13,0.52,1.0,0.33,0.00
95,0.23,1.00,0.60,0.68,0.03,0.0,1.00,1.00
96,0.37,0.08,0.99,0.92,0.24,0.0,0.00,0.32
97,0.16,0.76,0.18,0.72,0.34,0.0,1.00,0.00
98,0.79,0.72,0.80,0.22,0.97,1.0,0.67,1.00
99,0.79,0.42,0.09,0.79,0.59,0.0,0.33,0.00
100,0.74,0.08,0.84,0.85,0.07,0.0,0.67,0.00
101,0.09,0.52,0.38,0.52,1.00,0.0,1.00,0.32
102,0.95,0.50,0.91,0.48,0.86,0.0,1.00,0.00
103,0.88,0.24,0.12,0.58,0.00,0.0,0.00,0.32
104,0.93,0.42,0.17,0.68,0.34,0.0,0.33,0.00
105,0.63,0.76,0.48,0.16,0.52,1.0,0.33,1.00
106,0.14,0.51,0.15,0.37,0.59,0.0,1.00,0.00
107,0.19,0.50,0.60,0.61,1.00,0.0,0.33,1.00
108,0.16,0.31,0.43,0.40,0.52,1.0,0.00,1.00
109,0.26,0.00,0.01,0.07,0.76,0.0,0.67,0.00
110,0.77,0.50,0.89,0.12,0.31,0.0,0.33,1.00
111,0.74,0.72,0.58,0.93,0.59,0.0,1.00,0.00
112,0.51,0.04,0.80,0.23,0.17,0.0,0.67,0.00
113,0.53,0.07,0.65,0.46,0.62,0.0,0.67,1.00
114,0.84,0.35,0.03,0.03,0.10,0.0,0.00,1.00
115,0.79,0.50,0.58,0.87,0.90,0.0,1.00,0.32
116,1.00,0.07,0.09,0.11,0.41,0.0,0.33,1.00
117,0.91,0.76,0.81,0.79,0.79,0.0,1.00,0.32
118,0.49,0.50,0.17,0.49,0.45,0.0,0.67,1.00
119,0.60,0.34,0.69,0.06,0.07,0.0,1.00,0.00
120,0.79,0.50,0.75,0.90,0.31,0.0,0.33,1.00
121,0.00,0.72,0.56,0.85,0.17,0.0,0.33,0.00
122,0.79,0.46,0.39,0.59,0.00,0.0,0.00,0.00
123,0.84,0.80,0.85,0.55,0.76,1.0,0.33,0.00
124,0.30,0.44,0.08,0.50,0.79,0.0,0.33,0.32
125,0.05,0.64,0.03,0.36,0.90,0.0,1.00,1.00
126,0.00,0.39,0.91,0.81,0.45,0.0,1.00,0.00
127,0.09,1.00,0.93,0.59,0.24,0.0,0.67,0.00
128,0.58,0.19,0.58,0.06,0.62,0.0,0.00,0.32
129,0.30,0.80,0.08,0.88,0.45,0.0,1.00,1.00
130,0.88,0.64,0.52,0.87,0.31,0.0,0.33,1.00
131,0.60,0.24,0.62,0.12,0.55,0.0,0.67,0.32
132,0.19,0.50,0.84,0.01,0.28,0.0,1.00,0.32
133,0.33,0.22,0.78,0.55,0.97,0.0,0.00,1.00
134,0.33,0.24,0.20,0.62,0.17,0.0,0.00,0.32
135,0.58,0.64,0.27,0.78,0.34,0.0,0.67,1.00
136,0.95,0.55,0.79,0.77,0.83,0.0,0.67,1.00
137,0.28,0.34,0.70,0.60,0.21,0.0,0.67,0.00
138,0.72,0.19,0.85,0.80,0.55,0.0,0.67,0.00
139,0.88,0.46,0.39,0.32,0.93,0.0,0.67,1.00
140,0.72,0.46,0.20,0.96,0.93,0.0,0.33,1.00
141,0.07,0.62,0.62,0.05,0.00,0.0,0.33,1.00
142,0.67,1.00,0.69,0.74,0.72,0.0,1.00,1.00
143,0.84,1.00,0.50,0.42,0.14,0.0,0.00,1.00
144,0.51,0.31,0.32,0.97,0.28,0.0,0.33,1.00
145,0.88,0.02,0.98,1.00,0.59,1.0,0.33,0.32
146,0.33,0.50,0.88,0.92,0.79,0.0,0.33,1.00
147,0.98,0.50,0.25,0.32,0.90,0.0,1.00,0.32
148,0.65,0.31,0.57,0.24,0.69,0.0,0.67,0.32
149,0.81,0.64,0.79,0.83,0.03,0.0,1.00,1.00
150,0.28,0.87,0.27,0.63,0.97,1.0,0.00,1.00
151,0.72,1.00,0.93,0.98,0.86,0.0,0.00,0.32
152,0.14,0.52,0.50,0.74,0.34,0.0,0.00,0.32
153,0.49,0.46,0.63,0.14,0.90,0.0,0.00,1.00
154,0.63,0.75,0.14,0.89,0.93,0.0,0.33,1.00
155,0.02,0.24,0.79,0.35,0.17,0.0,0.33,0.32
156,0.95,0.90,0.97,0.29,0.86,0.0,1.00,0.32
157,0.12,0.08,0.59,0.63,0.24,0.0,0.67,0.32
158,0.63,0.80,0.70,0.66,0.10,0.0,0.00,0.00
159,0.63,0.18,0.02,0.16,0.59,0.0,1.00,0.32
160,1.00,0.18,0.10,0.48,0.93,1.0,0.33,0.00
161,1.00,0.19,0.73,0.39,0.34,0.0,0.33,1.00
162,0.44,0.55,0.48,0.48,0.14,0.0,0.67,1.00
163,0.67,0.14,0.36,0.51,0.48,0.0,0.67,0.32
164,0.23,0.52,0.26,0.85,0.93,0.0,0.67,1.00
165,0.63,0.39,0.61,0.69,0.59,0.0,1.00,1.00
166,0.56,0.50,0.26,0.66,0.03,0.0,0.33,1.00
167,0.88,0.80,0.97,0.82,0.72,0.0,0.33,1.00
168,0.74,0.31,0.18,0.80,0.34,1.0,0.67,0.00
169,0.00,0.72,0.57,0.17,0.86,0.0,0.00,0.00
170,0.60,0.24,0.60,0.77,0.83,0.0,0.67,0.32
171,0.28,0.75,0.36,0.26,0.41,0.0,1.00,0.32
172,0.93,0.46,0.60,0.53,0.10,0.0,0.67,0.32
173,0.05,0.08,0.29,0.79,0.72,0.0,0.67,1.00
174,0.88,0.08,0.87,0.09,0.21,0.0,1.00,1.00
175,0.12,0.39,0.55,0.55,0.97,0.0,0.67,0.00
176,0.16,0.75,0.74,0.34,0.34,1.0,0.33,0.00
177,0.60,1.00,0.93,0.25,0.72,0.0,0.00,0.32
178,0.19,0.80,0.10,0.73,0.79,0.0,0.67,0.00
179,0.84,0.08,0.62,0.62,0.10,0.0,1.00,0.00
180,0.74,1.00,0.48,0.58,0.93,0.0,0.00,0.00
181,0.95,0.52,0.87,0.66,0.48,0.0,1.00,0.00
182,1.00,0.50,0.20,0.69,0.00,0.0,0.00,0.00
183,0.53,1.00,0.82,0.42,0.76,0.0,0.00,0.32
184,0.33,0.75,1.00,0.62,0.07,0.0,0.67,0.32
185,0.72,0.14,0.29,1.00,0.45,0.0,0.33,0.00
186,0.72,0.45,0.84,0.96,0.17,0.0,0.67,0.32
187,0.53,0.80,0.13,0.33,0.59,0.0,1.00,1.00
188,0.93,0.08,0.16,0.07,0.83,0.0,1.00,0.00
189,0.26,0.62,0.63,0.72,0.00,0.0,0.00,1.00
190,0.88,0.80,0.60,0.90,0.17,0.0,0.00,0.32
191,0.02,0.55,0.81,0.60,0.17,0.0,0.33,0.32
192,0.05,0.42,0.95,0.23,0.69,0.0,0.67,1.00
193,0.84,0.55,0.15,0.00,0.52,0.0,1.00,0.32
194,0.37,0.52,0.30,0.30,0.97,0.0,0.00,0.00
195,0.02,0.80,0.69,0.03,0.14,0.0,0.33,1.00
196,0.02,0.00,0.95,0.60,0.55,0.0,1.00,0.00
197,0.63,0.62,0.27,0.83,0.31,0.0,0.00,1.00
198,0.51,0.01,1.00,0.20,0.93,0.0,1.00,0.32
199,0.84,0.55,0.97,0.49,0.69,0.0,0.33,1.00
200,0.72,0.46,0.51,0.81,0.59,0.0,0.33,1.00
201,0.74,0.72,0.78,0.44,0.21,0.0,1.00,0.00
202,0.00,0.18,0.46,0.55,0.07,0.0,0.67,0.32
203,0.42,0.72,0.76,0.19,0.41,0.0,1.00,0.00
204,0.02,0.52,0.98,0.45,0.48,1.0,0.00,0.32
205,1.00,0.39,0.66,0.82,0.66,0.0,0.67,0.00
206,0.58,0.00,0.15,0.95,0.62,0.0,0.00,1.00
207,0.72,0.19,0.08,0.28,0.07,0.0,1.00,0.00
208,0.12,0.55,0.52,0.32,0.10,0.0,0.67,0.32
209,0.72,0.19,0.42,0.62,0.14,0.0,0.00,0.32
210,0.07,0.24,0.54,0.78,0.00,0.0,1.00,1.00
211,0.23,0.24,0.19,0.59,0.10,0.0,1.00,0.32
212,0.37,0.46,0.14,0.76,0.38,0.0,0.67,0.00
213,0.86,0.02,0.55,0.88,0.93,0.0,1.00,1.00
214,0.53,0.46,0.94,0.75,0.90,0.0,0.33,0.32
215,0.09,1.00,0.27,0.15,0.79,0.0,0.00,0.32
216,0.77,0.31,0.77,0.20,0.31,0.0,0.00,0.00
217,0.12,0.07,0.94,0.60,0.76,0.0,1.00,0.00
218,0.49,0.75,0.48,0.69,0.83,1.0,1.00,1.00
219,0.23,0.97,0.12,0.07,0.69,1.0,0.33,0.32
220,0.35,0.02,0.95,0.19,0.97,0.0,0.67,0.00
221,0.74,0.08,0.30,0.37,0.86,0.0,1.00,1.00
222,0.19,0.39,0.25,0.82,0.66,1.0,1.00,0.32
223,0.12,0.68,0.50,0.48,0.79,0.0,1.00,0.32
224,0.35,0.07,0.34,0.38,0.83,0.0,1.00,1.00
225,0.65,0.31,0.53,0.21,0.41,1.0,0.00,1.00
226,0.05,0.80,0.76,0.68,0.76,0.0,1.00,0.00
227,0.44,0.87,0.52,0.98,0.45,0.0,0.00,0.32
228,0.81,0.64,0.21,0.15,0.76,0.0,1.00,0.32
229,0.42,0.64,0.63,0.83,0.14,0.0,0.67,0.32
230,0.58,0.14,0.83,0.93,0.10,0.0,0.33,1.00
231,0.05,0.18,0.36,0.70,0.45,0.0,0.67,0.00
232,0.42,0.45,0.23,0.64,0.31,0.0,1.00,0.32
233,0.44,0.76,0.86,0.54,0.55,0.0,1.00,1.00
234,0.72,0.18,0.22,0.47,0.31,0.0,1.00,0.32
235,0.14,0.08,0.70,0.15,0.86,0.0,0.67,0.00
236,0.93,0.04,0.14,0.49,0.21,0.0,1.00,0.32
237,0.74,0.18,0.80,0.76,0.52,1.0,0.67,0.00
238,0.91,0.64,0.76,0.43,0.00,0.0,0.00,0.00
239,0.88,0.55,0.88,0.56,0.55,0.0,0.33,0.32
240,0.40,0.39,0.81,0.65,0.69,0.0,0.33,0.32
241,0.91,0.80,0.16,0.39,0.97,0.0,0.67,0.00
242,0.00,0.04,0.71,0.09,0.28,0.0,0.00,1.00
243,0.23,0.31,0.80,0.23,0.17,0.0,0.67,0.00
244,0.63,1.00,0.52,0.40,0.62,0.0,0.00,0.32
245,0.56,0.04,0.00,0.51,0.41,0.0,1.00,0.32
246,0.51,0.62,0.84,0.74,0.07,0.0,0.00,1.00
247,0.70,0.64,0.36,0.92,0.21,0.0,0.00,0.00
248,0.67,0.34,0.07,0.53,0.72,0.0,0.00,0.00
249,0.95,0.02,0.94,0.50,0.28,0.0,0.33,0.00
250,0.79,0.22,0.58,0.80,0.72,0.0,0.00,0.32
251,0.14,0.76,0.39,0.19,0.14,0.0,1.00,0.00
252,0.35,0.90,0.65,0.76,0.31,1.0,1.00,1.00
253,0.58,0.64,0.38,0.78,0.76,0.0,1.00,0.32
254,0.02,0.76,0.33,0.68,0.55,0.0,0.00,0.32
255,0.00,0.42,0.93,0.13,0.38,0.0,0.67,0.00
256,0.26,0.55,0.26,0.05,0.76,0.0,0.67,1.00
257,0.09,0.52,0.06,0.34,0.52,0.0,1.00,0.32
258,0.84,0.51,0.35,0.66,0.07,0.0,0.33,0.32
259,0.72,0.24,0.60,0.82,1.00,0.0,0.67,0.00
260,0.19,0.22,0.75,0.35,0.83,0.0,0.00,0.00
261,0.93,0.14,0.90,0.28,0.72,0.0,0.67,1.00
262,0.79,0.39,0.53,0.31,0.28,0.0,1.00,0.00
263,0.42,0.80,0.58,0.07,0.97,0.0,0.33,1.00
264,0.35,0.75,0.20,0.11,0.48,0.0,0.67,0.32
265,0.05,0.42,0.60,0.04,0.14,0.0,0.67,1.00
266,0.44,0.46,0.88,0.65,0.76,0.0,1.00,1.00
267,0.53,0.00,0.16,0.13,0.41,0.0,0.33,1.00
268,0.74,0.97,0.47,0.21,0.45,0.0,0.33,0.32
269,0.53,0.24,0.75,0.69,0.66,1.0,1.00,0.00
270,0.23,0.35,0.39,0.53,0.48,0.0,0.00,0.32
271,0.16,0.87,0.09,0.80,0.52,0.0,0.67,0.00
272,0.81,0.14,0.63,0.01,0.76,0.0,0.00,1.00
273,0.86,0.04,0.71,0.36,0.41,0.0,0.67,1.00
274,0.91,0.80,0.51,0.77,0.55,0.0,0.67,1.00
275,0.44,0.76,0.71,0.35,0.76,0.0,0.00,1.00
276,0.79,0.87,0.72,0.27,0.24,0.0,1.00,1.00
277,0.56,0.68,0.99,0.37,0.69,0.0,1.00,0.00
278,0.79,0.39,0.65,0.81,0.03,0.0,0.67,0.00
279,0.56,0.97,0.85,0.76,0.14,0.0,1.00,1.00
280,0.65,0.76,0.39,0.78,0.17,0.0,0.67,0.32
281,0.40,0.00,0.75,0.87,0.38,0.0,1.00,0.32
282,0.40,0.34,0.24,0.86,0.59,0.0,0.67,1.00
283,0.02,0.01,0.69,0.23,1.00,0.0,1.00,0.00
284,0.79,0.42,0.57,0.72,0.72,0.0,0.33,0.32
285,0.35,0.34,0.88,0.59,0.72,0.0,0.00,0.32
286,0.93,0.34,0.27,0.71,0.00,0.0,0.33,0.32
287,0.81,0.14,0.17,0.80,1.00,0.0,0.00,1.00
288,0.74,0.68,0.31,0.37,0.55,1.0,0.00,0.32
289,0.07,0.22,0.36,0.88,1.00,0.0,0.67,0.32
290,0.74,0.72,0.70,0.05,0.34,0.0,0.00,0.32
291,0.30,0.18,0.22,0.70,0.31,0.0,0.33,0.32
292,0.47,0.22,0.84,0.79,0.62,0.0,0.33,0.00
293,0.44,0.04,0.05,0.68,0.45,1.0,1.00,1.00
294,0.16,0.51,0.15,0.62,0.86,0.0,0.33,1.00
295,0.14,0.00,0.08,0.81,0.31,0.0,1.00,0.00
296,0.05,0.50,0.11,0.13,0.48,0.0,0.00,0.00
297,0.37,0.55,0.24,0.28,0.93,0.0,0.33,1.00
298,0.74,0.02,0.05,0.78,0.62,1.0,0.00,0.32
299,0.26,0.42,0.81,0.66,0.10,0.0,0.33,0.32
300,0.49,0.46,0.09,0.81,0.03,1.0,0.33,1.00
301,0.49,1.00,0.32,0.42,0.28,0.0,1.00,0.32
302,0.67,0.24,0.77,0.48,0.31,0.0,0.00,0.00
303,0.86,1.00,0.18,0.23,0.93,0.0,0.33,0.32
304,0.86,0.51,0.91,0.44,0.34,0.0,0.67,0.32
305,0.16,0.24,0.78,0.99,0.45,0.0,0.00,0.32
306,0.60,0.00,0.89,0.88,0.21,0.0,0.00,1.00
307,0.60,0.75,0.19,0.22,0.76,0.0,0.00,0.00
308,0.77,0.34,0.72,0.23,0.48,0.0,1.00,0.32
309,0.47,0.75,0.11,1.00,0.72,0.0,0.67,1.00
310,0.67,0.24,0.43,0.31,0.62,0.0,0.00,0.32
311,0.74,0.50,0.21,0.22,0.72,0.0,0.33,0.00
312,0.63,0.90,0.71,0.06,0.48,0.0,0.33,0.32
313,0.74,0.34,0.01,0.16,1.00,0.0,1.00,0.00
314,0.09,0.45,1.00,0.36,0.93,0.0,0.33,0.32
315,0.42,0.14,0.67,0.67,0.79,0.0,0.00,0.00
316,0.07,1.00,0.95,0.14,0.24,0.0,0.33,0.32
317,0.79,0.08,0.23,0.11,0.34,0.0,0.00,0.00
318,0.37,0.76,0.07,0.78,0.97,0.0,0.33,0.32
319,1.00,0.31,0.57,0.91,0.28,0.0,0.67,0.32
320,0.63,0.52,0.64,0.20,0.48,1.0,1.00,1.00
321,0.67,0.24,0.00,0.50,0.00,0.0,1.00,1.00
322,0.65,1.00,0.79,0.12,1.00,0.0,0.67,0.00
323,0.12,0.07,0.51,0.12,0.00,0.0,0.67,0.32
324,0.79,0.19,0.74,0.30,0.62,0.0,1.00,0.00
325,0.93,0.45,0.07,0.89,0.07,0.0,0.67,1.00
326,0.84,0.42,0.65,0.55,0.31,0.0,0.00,0.00
327,0.53,0.04,0.95,0.66,0.24,0.0,0.33,0.00
328,0.65,0.22,0.45,0.69,0.48,1.0,1.00,1.00
329,0.70,0.42,0.89,0.62,0.31,0.0,0.67,0.32
330,0.79,0.14,0.24,0.64,0.00,0.0,0.00,0.00
331,0.74,0.64,0.77,0.76,0.97,0.0,1.00,1.00
332,0.47,0.51,0.35,0.20,0.59,0.0,0.67,0.32
333,0.72,0.02,0.73,0.90,0.03,1.0,1.00,1.00
334,0.51,0.64,0.16,0.62,0.62,0.0,0.67,0.00
335,0.74,0.64,0.83,0.70,0.41,0.0,1.00,0.32
336,0.05,0.34,0.65,0.97,0.72,0.0,0.00,0.32
337,0.40,0.04,0.58,0.54,0.00,0.0,0.00,1.00
338,0.56,0.46,0.92,0.25,0.03,1.0,0.33,1.00
339,0.95,0.76,0.42,0.65,0.97,0.0,1.00,1.00
340,0.70,0.42,0.72,0.91,0.52,0.0,0.33,0.32
341,0.05,0.34,0.37,0.70,0.48,1.0,1.00,0.32
342,0.91,0.97,0.73,0.51,0.41,1.0,0.67,0.00
343,0.53,0.76,0.30,0.88,0.52,0.0,0.67,0.32
344,0.72,0.90,0.45,0.20,0.55,0.0,0.33,0.00
345,0.49,0.45,0.58,0.25,0.69,0.0,1.00,1.00
346,0.51,0.08,0.11,0.79,0.97,0.0,0.33,1.00
347,0.02,0.31,0.24,0.93,0.97,0.0,0.00,0.32
348,0.60,0.80,0.24,0.50,0.21,0.0,0.33,1.00
349,0.95,0.18,0.21,0.18,0.79,0.0,0.33,1.00
350,0.02,0.18,0.42,0.19,0.86,0.0,0.67,0.32
351,0.58,1.00,0.36,0.39,0.55,0.0,0.33,0.00
352,0.37,0.64,0.13,0.30,0.21,0.0,1.00,0.32
353,0.91,0.87,0.50,0.95,0.41,0.0,0.67,0.00
354,0.74,0.14,0.42,0.52,0.14,0.0,0.33,0.32
355,0.19,0.68,0.79,0.94,0.86,0.0,0.00,0.32
356,0.98,0.19,0.68,0.30,0.55,0.0,0.33,1.00
357,0.88,0.80,0.42,0.11,0.07,0.0,0.33,0.32
358,0.65,0.18,0.85,0.16,0.21,0.0,0.33,0.32
359,0.95,0.50,0.95,0.21,0.86,0.0,0.67,0.00
360,0.58,0.04,0.40,0.48,0.55,0.0,1.00,1.00
361,0.79,0.18,0.80,0.25,0.21,0.0,0.00,0.00
362,0.56,0.50,0.83,0.45,0.69,0.0,0.33,0.00
363,0.53,1.00,0.55,0.72,0.00,0.0,1.00,1.00
364,0.28,0.68,0.40,0.89,0.55,0.0,1.00,1.00
365,0.14,0.55,0.55,0.87,1.00,1.0,0.67,1.00
366,0.81,0.08,0.23,0.94,0.55,0.0,0.00,0.32
367,0.44,0.19,0.10,0.33,0.34,0.0,0.67,1.00
368,0.00,0.75,0.12,0.03,0.83,1.0,1.00,1.00
369,0.16,0.01,0.55,0.95,0.90,0.0,1.00,1.00
370,0.35,0.00,0.82,0.96,0.97,0.0,1.00,0.00
371,0.30,0.04,0.71,0.27,0.07,0.0,0.67,0.00
372,0.26,0.39,0.74,0.55,0.48,1.0,0.00,0.32
373,0.51,0.80,0.27,0.41,0.97,0.0,0.33,0.00
374,0.33,0.55,0.56,0.18,0.69,0.0,0.67,0.32
375,0.63,0.42,0.49,0.76,0.34,0.0,1.00,0.00
376,0.77,0.75,0.77,0.39,0.86,0.0,0.67,1.00
377,0.02,0.76,0.25,0.74,0.93,0.0,1.00,0.00
378,0.72,0.46,0.17,0.72,0.52,0.0,0.33,0.32
379,0.51,0.76,0.18,0.91,0.83,0.0,0.33,0.00
380,0.49,0.68,0.63,0.85,0.72,0.0,0.00,1.00
381,0.56,0.93,0.71,0.15,0.93,0.0,1.00,0.32
382,0.49,0.51,0.66,0.66,0.28,0.0,0.00,1.00
383,0.49,0.35,0.90,0.30,0.79,0.0,0.00,1.00
384,0.95,0.22,0.18,0.09,0.79,0.0,0.33,0.32
385,0.12,0.51,0.28,0.93,0.00,0.0,0.67,1.00
386,0.33,1.00,0.54,0.60,0.97,0.0,0.67,1.00
387,0.98,0.80,0.15,0.21,0.83,0.0,0.00,0.00
388,0.84,0.18,0.46,0.61,0.72,0.0,0.33,1.00
389,0.74,0.55,0.16,0.27,0.52,0.0,1.00,1.00
390,0.16,0.72,0.86,0.59,0.28,0.0,0.67,1.00
391,1.00,0.04,0.64,0.81,0.62,0.0,0.00,1.00
392,1.00,0.39,0.12,0.02,0.38,0.0,0.67,0.32
393,0.09,0.51,0.20,0.90,0.62,1.0,0.67,0.00
394,0.88,0.00,0.67,0.52,0.72,1.0,1.00,1.00
395,0.07,0.76,0.18,0.21,0.28,0.0,0.33,1.00
396,0.12,0.72,0.13,0.87,0.21,0.0,1.00,0.32
397,0.72,0.62,0.70,0.04,0.45,0.0,0.33,1.00
398,0.67,0.93,0.57,0.63,0.97,0.0,0.67,0.32
399,0.79,0.72,0.69,0.58,0.62,0.0,0.00,0.00
400,0.91,0.64,0.84,0.23,0.62,1.0,1.00,0.00
401,0.35,1.00,0.19,0.50,0.03,0.0,0.33,1.00
402,0.28,0.55,0.33,0.37,0.28,1.0,0.67,1.00
403,0.95,0.75,0.25,0.35,0.41,0.0,0.33,1.00
404,0.67,0.31,0.78,0.99,0.48,0.0,0.33,0.32
405,0.42,0.39,0.52,0.52,0.07,0.0,0.33,1.00
406,0.37,0.24,0.13,0.10,0.34,0.0,0.67,1.00
407,0.42,0.46,0.79,0.55,0.69,0.0,0.00,0.00
408,0.63,0.01,0.89,0.30,0.45,0.0,0.00,1.00
409,0.58,0.64,0.38,0.03,1.00,0.0,0.00,0.00
410,0.84,0.90,0.37,0.67,0.83,0.0,0.33,1.00
411,0.58,0.45,0.71,0.48,0.24,0.0,0.67,0.00
412,0.51,0.46,0.89,0.20,0.59,0.0,0.33,1.00
413,0.19,0.97,0.52,0.89,0.62,0.0,0.00,0.00
414,0.26,0.90,0.18,0.59,0.52,0.0,0.00,0.32
415,0.00,0.04,0.26,0.99,0.03,1.0,0.67,0.00
416,0.00,0.62,0.64,0.12,0.24,0.0,0.33,0.00
417,0.77,0.01,0.26,0.53,0.72,0.0,1.00,0.00
418,0.72,0.08,0.19,0.04,0.17,0.0,1.00,1.00
419,0.56,0.45,0.75,1.00,0.38,0.0,0.00,1.00
420,0.91,0.18,0.63,0.00,0.48,0.0,0.67,1.00
421,0.00,0.22,0.78,1.00,0.83,0.0,0.33,0.32
422,0.35,0.14,0.28,0.26,0.24,0.0,0.33,0.32
423,0.88,0.08,0.40,0.34,0.10,0.0,0.00,0.00
424,0.09,0.80,0.27,0.23,0.48,0.0,0.00,0.32
425,0.49,0.42,0.46,0.36,0.93,1.0,0.33,0.00
426,0.65,0.34,0.84,0.23,0.66,1.0,0.33,0.00
427,0.05,0.51,0.61,0.47,0.83,0.0,0.00,0.00
428,0.26,0.39,0.15,0.99,0.55,0.0,0.33,0.32
429,0.58,0.18,0.14,0.35,0.41,0.0,1.00,1.00
430,0.35,0.90,0.89,0.19,0.59,0.0,0.00,0.32
431,0.84,0.93,0.31,0.97,0.03,0.0,0.33,0.00
432,0.49,0.50,0.95,0.48,0.41,0.0,0.00,0.00
433,0.65,0.52,0.70,0.70,0.41,1.0,0.67,0.32
434,0.30,0.24,0.87,0.47,0.72,1.0,0.00,0.00
435,0.63,0.76,0.81,0.75,0.48,0.0,0.00,0.00
436,0.09,0.76,0.59,0.65,0.66,0.0,0.67,0.32
437,0.67,0.44,0.67,0.13,0.97,0.0,1.00,0.32
438,0.09,0.46,0.56,0.64,0.90,0.0,0.33,0.32
439,0.26,0.52,0.84,0.34,0.31,0.0,0.67,0.00
440,0.35,0.55,1.00,0.53,0.97,0.0,0.00,0.00
441,0.58,0.22,0.66,0.08,0.07,1.0,0.33,1.00
442,0.58,0.97,0.12,0.15,0.62,0.0,0.67,1.00
443,0.47,0.18,0.64,0.22,0.07,0.0,0.33,0.32
444,0.88,0.02,0.62,0.65,0.72,0.0,0.33,1.00
445,0.81,0.45,0.20,0.96,0.45,0.0,0.67,0.00
446,0.74,0.97,0.14,0.12,0.24,0.0,0.33,1.00
447,0.67,0.14,0.71,0.68,0.90,0.0,1.00,0.00
448,0.84,0.64,0.52,0.29,0.76,0.0,0.67,0.32
449,0.51,0.44,0.92,0.69,1.00,0.0,1.00,0.32
450,0.21,0.44,0.71,0.65,0.10,0.0,0.00,0.00
451,0.09,0.46,0.76,0.34,0.90,1.0,0.33,1.00
452,0.81,0.80,0.52,0.58,0.93,0.0,0.00,0.32
453,0.77,0.80,0.96,0.82,0.66,0.0,0.00,0.32
454,0.70,0.45,0.03,0.86,0.34,0.0,0.33,1.00
455,0.21,0.90,0.76,0.02,0.86,0.0,0.67,1.00
456,0.42,0.55,0.93,0.33,0.34,0.0,0.33,0.00
457,0.72,0.24,0.07,0.20,0.90,1.0,0.00,1.00
458,0.00,0.50,0.93,0.92,1.00,1.0,0.00,1.00
459,0.09,0.24,0.74,0.53,0.34,0.0,0.67,1.00
460,0.07,0.18,0.27,0.54,0.03,0.0,0.33,0.00
461,0.35,0.55,0.83,0.82,1.00,0.0,0.00,0.00
462,0.53,0.18,0.34,0.39,0.55,0.0,1.00,0.32
463,0.35,1.00,0.94,0.05,0.28,0.0,0.00,0.00
464,0.02,0.18,0.72,0.42,0.93,0.0,0.00,0.32

In [268]:
from sklearn.model_selection import train_test_split

In [269]:
X = arr2.drop(columns = ["Default"])

C:\Users\gopal\AppData\Local\Temp\ipykernel_7896\3521516612.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X = arr2.drop(columns = ["Default"])

In [270]:
y = arr2["Default"]

In [292]:
print(y.value_counts())

(Default,)
0.0           862
1.0           138
Name: count, dtype: int64

In [272]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.5 ,stratify=y, random_state=12)

In [273]:
y_train = y_train.astype(int)

In [274]:
X_train

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status
108,0.16,0.31,0.43,0.40,0.52,0.00,1.00
754,0.67,0.93,0.64,0.15,0.66,1.00,1.00
131,0.60,0.24,0.62,0.12,0.55,0.67,0.32
899,0.12,0.80,0.08,0.35,0.93,0.33,0.32
141,0.07,0.62,0.62,0.05,0.00,0.33,1.00
874,0.49,0.62,0.36,0.62,0.14,0.00,0.00
652,0.58,0.18,0.20,0.84,0.79,0.33,0.32
52,0.16,0.01,0.14,0.08,0.59,0.00,1.00
660,0.37,0.24,0.80,0.39,0.07,0.33,1.00
714,0.07,1.00,0.04,0.66,0.34,0.33,1.00
369,0.16,0.01,0.55,0.95,0.90,1.00,1.00
885,0.05,0.55,0.43,0.86,0.76,0.67,0.00
360,0.58,0.04,0.40,0.48,0.55,1.00,1.00
567,0.26,0.75,0.93,0.46,0.21,0.00,0.32
878,0.07,0.39,0.16,0.61,0.59,0.67,0.32
420,0.91,0.18,0.63,0.00,0.48,0.67,1.00
242,0.00,0.04,0.71,0.09,0.28,0.00,1.00
362,0.56,0.50,0.83,0.45,0.69,0.33,0.00
755,0.95,0.34,0.14,0.59,1.00,0.33,0.32
133,0.33,0.22,0.78,0.55,0.97,0.00,1.00
500,0.14,0.44,0.10,0.80,0.76,0.33,0.00
96,0.37,0.08,0.99,0.92,0.24,0.00,0.32
838,0.56,0.31,0.73,0.39,0.90,0.33,0.00
120,0.79,0.50,0.75,0.90,0.31,0.33,1.00
510,0.19,0.55,0.47,0.28,0.31,0.00,0.32
269,0.53,0.24,0.75,0.69,0.66,1.00,0.00
558,0.30,0.93,1.00,0.05,0.69,0.00,0.00
818,0.79,0.34,0.31,0.62,0.66,0.00,1.00
810,0.49,0.80,0.95,0.59,0.48,1.00,1.00
736,0.47,0.93,0.35,0.28,0.59,0.00,0.00
728,1.00,0.80,0.52,1.00,0.21,0.67,1.00
680,0.72,1.00,0.57,0.00,0.52,0.33,0.00
505,0.56,0.75,0.86,0.38,0.31,0.67,1.00
241,0.91,0.80,0.16,0.39,0.97,0.67,0.00
103,0.88,0.24,0.12,0.58,0.00,0.00,0.32
561,0.79,0.31,0.10,0.98,0.41,0.33,1.00
982,0.91,0.68,0.00,0.80,0.69,1.00,1.00
863,1.00,0.72,0.12,0.00,1.00,0.67,1.00
481,0.21,0.76,0.84,0.88,0.21,0.67,0.00
359,0.95,0.50,0.95,0.21,0.86,0.67,0.00
965,0.23,1.00,0.15,0.94,0.41,0.33,0.32
345,0.49,0.45,0.58,0.25,0.69,1.00,1.00
834,0.40,0.87,0.62,0.08,0.21,0.33,1.00
467,0.60,0.90,0.33,0.79,0.97,0.00,0.32
884,0.19,0.19,0.74,0.12,0.03,1.00,1.00
707,0.42,0.90,0.41,0.64,0.59,0.67,0.00
64,0.40,0.80,0.97,0.57,0.10,0.33,0.00
29,0.60,0.55,0.57,0.41,0.41,0.33,1.00
256,0.26,0.55,0.26,0.05,0.76,0.67,1.00
919,0.30,0.50,0.84,0.68,0.38,0.67,0.32
13,0.91,0.24,0.59,0.64,0.83,0.33,1.00
175,0.12,0.39,0.55,0.55,0.97,0.67,0.00
868,0.12,0.42,0.70,0.57,0.93,1.00,0.00
372,0.26,0.39,0.74,0.55,0.48,0.00,0.32
159,0.63,0.18,0.02,0.16,0.59,1.00,0.32
388,0.84,0.18,0.46,0.61,0.72,0.33,1.00
299,0.26,0.42,0.81,0.66,0.10,0.33,0.32
855,0.05,0.31,0.02,0.15,0.38,0.33,0.32
421,0.00,0.22,0.78,1.00,0.83,0.33,0.32
586,0.00,0.08,0.28,0.98,0.72,1.00,0.00
441,0.58,0.22,0.66,0.08,0.07,0.33,1.00
638,0.51,0.50,0.44,0.42,0.34,0.67,1.00
418,0.72,0.08,0.19,0.04,0.17,1.00,1.00
719,0.63,0.34,0.84,0.78,0.28,0.00,1.00
668,0.79,0.34,0.86,0.45,0.83,0.00,1.00
916,0.26,0.07,0.04,0.57,0.52,1.00,1.00
201,0.74,0.72,0.78,0.44,0.21,1.00,0.00
258,0.84,0.51,0.35,0.66,0.07,0.33,0.32
142,0.67,1.00,0.69,0.74,0.72,1.00,1.00
387,0.98,0.80,0.15,0.21,0.83,0.00,0.00
460,0.07,0.18,0.27,0.54,0.03,0.33,0.00
603,0.05,0.44,0.60,0.10,0.79,1.00,0.32
484,0.65,0.55,0.51,0.02,0.55,1.00,1.00
499,0.93,0.75,0.23,0.13,0.52,0.33,0.32
455,0.21,0.90,0.76,0.02,0.86,0.67,1.00
548,0.79,0.08,0.80,0.96,0.48,0.67,1.00
790,0.42,0.55,0.40,0.49,1.00,0.00,1.00
777,0.23,0.55,0.93,0.74,0.72,0.33,0.32
386,0.33,1.00,0.54,0.60,0.97,0.67,1.00
254,0.02,0.76,0.33,0.68,0.55,0.00,0.32
126,0.00,0.39,0.91,0.81,0.45,1.00,0.00
178,0.19,0.80,0.10,0.73,0.79,0.67,0.00
915,0.44,0.08,0.38,0.04,0.83,0.67,0.00
488,0.02,0.50,0.57,0.74,0.38,0.67,1.00
673,0.02,0.18,0.05,0.82,0.34,0.00,1.00
235,0.14,0.08,0.70,0.15,0.86,0.67,0.00
298,0.74,0.02,0.05,0.78,0.62,0.00,0.32
195,0.02,0.80,0.69,0.03,0.14,0.33,1.00
363,0.53,1.00,0.55,0.72,0.00,1.00,1.00
770,0.28,0.72,0.68,0.51,0.72,1.00,1.00
911,0.07,0.50,0.19,0.78,0.03,0.00,0.00
787,0.60,0.46,0.41,0.90,0.76,0.67,1.00
318,0.37,0.76,0.07,0.78,0.97,0.33,0.32
826,0.53,0.44,0.21,0.98,0.31,1.00,1.00
413,0.19,0.97,0.52,0.89,0.62,0.00,0.00
956,0.77,0.18,0.73,0.73,1.00,0.33,0.00
979,0.95,0.31,0.84,0.30,0.17,0.67,0.32
882,0.70,0.22,0.51,0.33,0.76,0.67,0.32
866,0.93,0.55,0.63,0.30,0.31,0.00,1.00
68,0.21,0.24,0.94,0.71,0.90,0.00,0.00
331,0.74,0.64,0.77,0.76,0.97,1.00,1.00
862,0.91,1.00,0.50,0.36,0.97,0.00,1.00
288,0.74,0.68,0.31,0.37,0.55,0.00,0.32
12,0.81,1.00,0.34,0.24,0.86,0.67,0.32
326,0.84,0.42,0.65,0.55,0.31,0.00,0.00
224,0.35,0.07,0.34,0.38,0.83,1.00,1.00
0,0.88,0.24,0.14,0.95,0.52,0.00,0.32
22,0.02,0.34,0.01,0.79,0.90,0.00,0.00
197,0.63,0.62,0.27,0.83,0.31,0.00,1.00
443,0.47,0.18,0.64,0.22,0.07,0.33,0.32
344,0.72,0.90,0.45,0.20,0.55,0.33,0.00
251,0.14,0.76,0.39,0.19,0.14,1.00,0.00
688,0.74,0.75,0.24,0.60,0.93,1.00,0.00
106,0.14,0.51,0.15,0.37,0.59,1.00,0.00
594,0.70,0.42,0.38,0.85,0.79,1.00,0.32
581,0.65,0.34,0.26,0.70,0.00,0.00,0.00
864,0.42,0.75,0.46,0.74,0.79,1.00,1.00
31,0.63,0.68,0.61,0.87,0.00,0.00,0.32
570,1.00,0.51,0.12,0.95,0.48,0.33,1.00
280,0.65,0.76,0.39,0.78,0.17,0.67,0.32
193,0.84,0.55,0.15,0.00,0.52,1.00,0.32
186,0.72,0.45,0.84,0.96,0.17,0.67,0.32
221,0.74,0.08,0.30,0.37,0.86,1.00,1.00
681,0.23,0.24,0.25,0.94,0.62,0.67,0.32
229,0.42,0.64,0.63,0.83,0.14,0.67,0.32
625,0.84,0.46,0.35,0.37,0.97,0.00,0.00
410,0.84,0.90,0.37,0.67,0.83,0.33,1.00
729,0.09,0.07,0.66,0.93,0.10,0.67,0.32
703,0.84,0.04,0.78,0.28,0.45,1.00,0.32
62,0.07,0.46,0.28,0.97,0.48,0.33,0.32
654,0.63,0.80,0.41,0.65,0.55,1.00,0.32
6,0.88,0.68,0.38,0.29,0.93,0.67,0.32
385,0.12,0.51,0.28,0.93,0.00,0.67,1.00
20,0.67,0.75,0.04,0.68,0.52,0.00,1.00
873,0.74,0.97,0.95,0.48,0.10,1.00,0.00
335,0.74,0.64,0.83,0.70,0.41,1.00,0.32
347,0.02,0.31,0.24,0.93,0.97,0.00,0.32
960,0.00,0.80,0.14,0.71,0.55,0.00,0.32
683,0.58,0.24,0.05,0.95,0.79,0.33,1.00
692,0.00,0.93,0.44,0.89,0.62,0.00,1.00
137,0.28,0.34,0.70,0.60,0.21,0.67,0.00
545,0.42,0.14,0.93,0.72,1.00,0.67,1.00
661,0.19,0.76,0.66,0.80,0.07,0.00,1.00
380,0.49,0.68,0.63,0.85,0.72,0.00,1.00
636,0.05,0.55,0.52,0.98,0.07,0.33,0.00
145,0.88,0.02,0.98,1.00,0.59,0.33,0.32
786,0.05,0.00,0.55,0.20,0.66,0.00,1.00
569,0.21,0.55,0.24,0.41,0.48,0.67,0.32
851,0.44,0.90,0.72,0.20,0.83,0.67,0.32
350,0.02,0.18,0.42,0.19,0.86,0.67,0.32
412,0.51,0.46,0.89,0.20,0.59,0.33,1.00
797,0.47,0.76,0.96,0.30,0.79,0.00,0.00
56,0.81,0.62,0.30,0.00,0.07,0.00,1.00
615,0.56,1.00,0.74,0.92,0.72,0.67,0.32
524,0.51,0.64,0.08,0.43,0.90,0.00,1.00
104,0.93,0.42,0.17,0.68,0.34,0.33,0.00
886,0.70,0.24,0.05,0.18,0.34,0.00,1.00
364,0.28,0.68,0.40,0.89,0.55,1.00,1.00
832,0.51,0.90,0.38,0.90,0.03,0.00,0.00
667,0.28,0.52,0.37,0.83,0.62,0.33,1.00
339,0.95,0.76,0.42,0.65,0.97,1.00,1.00
378,0.72,0.46,0.17,0.72,0.52,0.33,0.32
238,0.91,0.64,0.76,0.43,0.00,0.00,0.00
553,0.51,0.76,0.25,0.31,0.97,1.00,0.32
891,0.70,1.00,0.14,0.08,0.17,0.33,0.32
597,0.88,0.55,0.87,0.32,0.52,0.67,0.00
867,0.84,0.52,0.77,0.93,0.21,0.00,0.00
761,0.37,0.18,0.56,0.57,1.00,0.67,1.00
321,0.67,0.24,0.00,0.50,0.00,1.00,1.00
994,0.37,0.24,0.56,0.56,0.24,1.00,0.32
307,0.60,0.75,0.19,0.22,0.76,0.00,0.00
858,0.81,0.75,0.87,0.35,0.24,0.67,0.32
704,0.84,0.45,0.21,0.71,0.34,0.00,1.00
245,0.56,0.04,0.00,0.51,0.41,1.00,0.32
292,0.47,0.22,0.84,0.79,0.62,0.33,0.00
253,0.58,0.64,0.38,0.78,0.76,1.00,0.32
252,0.35,0.90,0.65,0.76,0.31,1.00,1.00
90,0.53,0.14,0.71,0.52,0.83,1.00,0.32
750,0.86,0.76,0.23,0.03,0.48,1.00,0.32
390,0.16,0.72,0.86,0.59,0.28,0.67,1.00
947,0.86,0.52,0.57,0.26,0.07,0.00,0.00
77,0.47,0.64,0.50,1.00,0.31,0.00,0.00
496,0.21,0.90,0.92,0.02,0.97,1.00,0.32
593,0.12,0.52,0.49,0.28,0.93,0.00,0.00
48,0.44,0.75,0.00,0.12,0.52,0.00,1.00
508,0.21,1.00,0.63,0.71,0.72,0.33,0.32
803,0.58,0.76,0.65,0.86,0.28,0.67,0.32
626,0.81,0.24,0.31,0.14,0.31,0.67,1.00
489,0.79,0.08,0.68,0.04,0.97,1.00,0.00
351,0.58,1.00,0.36,0.39,0.55,0.33,0.00
14,0.53,0.24,0.60,0.36,0.31,0.00,0.00
589,0.14,0.34,0.78,0.69,0.69,0.33,0.32
75,0.51,1.00,0.84,0.81,0.83,0.33,0.32
959,0.79,0.02,0.05,0.66,0.41,1.00,1.00
18,0.53,0.31,0.31,0.87,0.72,0.33,0.32
37,0.14,0.52,0.63,0.99,0.28,0.33,0.00
633,0.33,0.02,0.64,0.79,0.97,0.00,0.00
876,0.12,0.46,0.55,0.44,0.72,0.33,0.32
404,0.67,0.31,0.78,0.99,0.48,0.33,0.32
98,0.79,0.72,0.80,0.22,0.97,0.67,1.00
938,0.44,1.00,0.41,0.06,0.52,1.00,0.32
423,0.88,0.08,0.40,0.34,0.10,0.00,0.00
365,0.14,0.55,0.55,0.87,1.00,0.67,1.00
151,0.72,1.00,0.93,0.98,0.86,0.00,0.32
134,0.33,0.24,0.20,0.62,0.17,0.00,0.32
416,0.00,0.62,0.64,0.12,0.24,0.33,0.00
940,0.84,0.68,0.65,0.09,0.38,0.33,0.00
962,0.49,0.87,0.48,0.37,0.14,0.00,0.32
260,0.19,0.22,0.75,0.35,0.83,0.00,0.00
93,0.16,0.42,0.94,0.11,0.34,0.67,1.00
645,0.86,0.22,0.66,0.05,0.93,1.00,0.00
440,0.35,0.55,1.00,0.53,0.97,0.00,0.00
708,0.37,0.93,0.02,0.50,0.90,0.67,1.00
8,0.51,0.02,0.94,0.18,0.97,0.33,0.32
852,0.56,0.01,0.70,0.28,0.24,1.00,0.32
267,0.53,0.00,0.16,0.13,0.41,0.33,1.00
397,0.72,0.62,0.70,0.04,0.45,0.33,1.00
54,0.30,1.00,0.20,0.36,0.72,1.00,0.00
516,0.88,0.50,0.44,0.32,0.72,0.67,0.00
794,0.63,0.80,0.65,0.51,0.41,0.33,0.32
84,0.65,0.75,1.00,0.77,0.69,0.33,1.00
522,0.26,0.39,0.55,0.32,0.24,1.00,0.32
160,1.00,0.18,0.10,0.48,0.93,0.33,0.00
658,0.81,0.64,0.87,0.09,0.34,0.00,0.00
999,0.91,0.46,0.06,0.64,0.17,0.33,1.00
95,0.23,1.00,0.60,0.68,0.03,1.00,1.00
697,0.09,0.51,0.77,0.60,0.72,0.67,0.00
819,0.33,0.80,0.52,0.07,0.93,1.00,0.00
289,0.07,0.22,0.36,0.88,1.00,0.67,0.32
540,0.19,0.76,0.69,0.41,0.86,0.33,0.00
930,0.09,0.24,0.24,0.51,0.28,0.00,0.32
981,0.40,0.34,0.25,0.28,0.93,1.00,0.32
140,0.72,0.46,0.20,0.96,0.93,0.33,1.00
325,0.93,0.45,0.07,0.89,0.07,0.67,1.00
998,0.91,0.35,0.13,0.87,0.83,1.00,0.32
756,0.37,0.55,0.24,0.21,0.17,0.00,1.00
760,0.21,0.24,0.43,0.48,0.86,0.00,0.32
931,0.51,0.02,0.69,0.25,0.24,1.00,0.00
394,0.88,0.00,0.67,0.52,0.72,1.00,1.00
641,0.21,0.34,0.99,0.89,0.62,0.33,0.00
971,0.47,0.90,0.84,0.85,0.10,0.33,0.00
665,0.63,0.24,0.50,0.01,0.97,0.67,0.32
117,0.91,0.76,0.81,0.79,0.79,1.00,0.32
881,0.67,0.76,0.57,0.20,0.79,0.67,0.32
904,0.23,1.00,0.00,0.95,0.76,1.00,0.32
212,0.37,0.46,0.14,0.76,0.38,0.67,0.00
537,0.93,0.87,0.18,0.64,0.59,0.67,0.00
162,0.44,0.55,0.48,0.48,0.14,0.67,1.00
588,0.37,0.14,0.15,0.74,0.97,1.00,0.00
715,0.00,0.62,0.32,0.01,0.69,1.00,1.00
432,0.49,0.50,0.95,0.48,0.41,0.00,0.00
824,0.51,0.52,0.60,0.56,0.55,0.33,0.00
44,0.30,0.55,0.92,0.32,0.41,0.33,1.00
527,0.93,0.50,0.52,0.97,1.00,0.00,0.32
698,0.70,0.14,0.54,0.25,0.55,0.00,0.00
888,0.84,0.75,0.72,0.23,0.45,0.00,0.00
670,0.40,0.68,0.95,0.03,0.97,1.00,0.00
447,0.67,0.14,0.71,0.68,0.90,1.00,0.00
502,0.23,0.76,0.65,0.28,0.69,0.67,0.00
327,0.53,0.04,0.95,0.66,0.24,0.33,0.00
263,0.42,0.80,0.58,0.07,0.97,0.33,1.00
822,0.58,0.02,0.20,0.31,0.76,0.33,1.00
844,0.88,0.34,0.91,0.29,0.66,0.00,1.00
587,0.49,0.34,0.46,0.31,0.17,0.00,0.00
464,0.02,0.18,0.72,0.42,0.93,0.00,0.32
997,0.30,0.64,0.25,0.13,1.00,0.67,0.00
340,0.70,0.42,0.72,0.91,0.52,0.33,0.32
483,1.00,0.46,0.97,0.29,0.66,0.67,1.00
81,0.58,0.45,0.81,0.99,0.24,0.00,0.00
710,0.30,0.24,0.04,0.82,0.72,1.00,0.32
592,0.81,0.22,0.13,0.21,0.14,1.00,0.32
905,0.16,0.45,0.25,0.44,0.31,1.00,1.00
515,0.40,0.35,0.68,0.15,0.34,0.67,1.00
206,0.58,0.00,0.15,0.95,0.62,0.00,1.00
623,0.47,0.90,0.62,0.41,0.97,0.33,0.00
963,0.65,0.22,0.23,0.03,0.17,1.00,1.00
795,0.95,0.75,0.18,0.07,0.90,0.00,1.00
523,0.28,0.50,0.87,0.04,0.41,1.00,1.00
261,0.93,0.14,0.90,0.28,0.72,0.67,1.00
333,0.72,0.02,0.73,0.90,0.03,1.00,1.00
1,0.65,0.75,0.86,0.03,0.17,1.00,0.32
16,0.49,0.42,0.22,0.41,0.48,0.33,0.00
324,0.79,0.19,0.74,0.30,0.62,1.00,0.00
606,0.44,0.76,0.86,0.96,0.21,1.00,0.00
353,0.91,0.87,0.50,0.95,0.41,0.67,0.00
733,0.51,0.08,0.24,0.31,0.38,1.00,0.32
407,0.42,0.46,0.79,0.55,0.69,0.00,0.00
196,0.02,0.00,0.95,0.60,0.55,1.00,0.00
694,0.12,1.00,0.53,0.46,0.38,0.67,0.00
735,0.84,0.87,0.00,0.83,0.72,0.33,0.32
38,0.47,1.00,0.84,0.07,0.10,0.00,1.00
314,0.09,0.45,1.00,0.36,0.93,0.33,0.32
953,0.30,0.64,0.51,0.73,0.10,0.00,1.00
442,0.58,0.97,0.12,0.15,0.62,0.67,1.00
459,0.09,0.24,0.74,0.53,0.34,0.67,1.00
83,0.93,0.51,0.70,0.51,0.55,0.67,1.00
883,0.53,1.00,0.34,0.35,0.72,0.33,0.32
192,0.05,0.42,0.95,0.23,0.69,0.67,1.00
146,0.33,0.50,0.88,0.92,0.79,0.33,1.00
476,0.26,0.64,0.24,0.04,0.86,1.00,1.00
675,0.67,0.76,0.76,0.53,0.31,0.67,1.00
158,0.63,0.80,0.70,0.66,0.10,0.00,0.00
436,0.09,0.76,0.59,0.65,0.66,0.67,0.32
854,0.21,0.35,0.17,0.35,0.24,0.33,0.32
913,0.44,0.00,0.68,0.93,0.72,0.67,1.00
157,0.12,0.08,0.59,0.63,0.24,0.67,0.32
685,0.49,0.68,0.43,0.90,0.45,0.00,1.00
297,0.37,0.55,0.24,0.28,0.93,0.33,1.00
503,0.65,0.72,0.54,0.17,0.86,0.00,1.00
49,0.63,0.97,0.53,0.88,0.17,0.67,1.00
194,0.37,0.52,0.30,0.30,0.97,0.00,0.00
627,0.79,0.02,0.73,0.22,0.07,0.33,1.00
214,0.53,0.46,0.94,0.75,0.90,0.33,0.32
445,0.81,0.45,0.20,0.96,0.45,0.67,0.00
662,0.74,0.52,0.50,0.29,0.52,0.00,0.00
541,0.14,0.64,0.67,0.43,0.76,0.67,0.00
831,0.05,0.76,0.19,0.69,0.34,0.67,1.00
415,0.00,0.04,0.26,0.99,0.03,0.67,0.00
174,0.88,0.08,0.87,0.09,0.21,1.00,1.00
226,0.05,0.80,0.76,0.68,0.76,1.00,0.00
839,0.84,0.93,0.93,0.56,0.66,1.00,1.00
747,0.33,0.34,0.84,0.59,0.76,0.00,1.00
856,0.93,0.68,0.26,0.89,0.79,0.33,1.00
435,0.63,0.76,0.81,0.75,0.48,0.00,0.00
276,0.79,0.87,0.72,0.27,0.24,1.00,1.00
939,0.00,1.00,0.89,0.58,0.28,0.33,1.00
648,0.63,0.42,0.60,0.92,0.07,0.00,0.00
717,0.72,0.76,0.86,0.64,0.14,0.00,1.00
121,0.00,0.72,0.56,0.85,0.17,0.33,0.00
45,0.19,0.52,0.78,0.50,0.45,1.00,0.32
167,0.88,0.80,0.97,0.82,0.72,0.33,1.00
507,0.81,0.24,0.83,0.16,0.69,1.00,1.00
15,0.05,0.51,0.81,0.69,0.69,1.00,0.00
925,0.98,1.00,0.68,0.22,0.48,0.00,1.00
745,0.40,0.18,0.01,0.91,0.52,1.00,1.00
936,0.91,0.90,0.61,0.21,0.59,1.00,0.32
793,0.40,0.87,0.36,0.51,0.52,0.00,0.00
649,0.16,0.19,0.04,0.55,0.72,0.33,1.00
833,0.98,0.02,0.72,0.69,0.59,0.67,0.00
417,0.77,0.01,0.26,0.53,0.72,1.00,0.00
573,0.14,0.80,0.29,0.21,0.76,1.00,0.00
574,0.28,0.55,0.87,0.10,0.17,0.00,0.00
804,0.77,1.00,0.33,0.33,0.07,0.00,1.00
370,0.35,0.00,0.82,0.96,0.97,1.00,0.00
231,0.05,0.18,0.36,0.70,0.45,0.67,0.00
78,0.35,0.18,0.64,0.26,0.59,0.33,1.00
367,0.44,0.19,0.10,0.33,0.34,0.67,1.00
433,0.65,0.52,0.70,0.70,0.41,0.67,0.32
271,0.16,0.87,0.09,0.80,0.52,0.67,0.00
449,0.51,0.44,0.92,0.69,1.00,1.00,0.32
639,0.23,0.35,0.29,0.96,0.90,0.00,0.32
659,0.60,0.80,0.21,0.18,0.86,0.00,1.00
444,0.88,0.02,0.62,0.65,0.72,0.33,1.00
806,0.58,0.35,0.65,0.51,0.66,0.33,0.00
651,0.81,0.72,0.19,0.48,0.45,0.00,1.00
341,0.05,0.34,0.37,0.70,0.48,1.00,0.32
25,0.26,0.75,0.45,0.72,0.10,0.67,0.00
419,0.56,0.45,0.75,1.00,0.38,0.00,1.00
695,0.63,0.75,0.34,0.16,0.59,1.00,0.32
575,0.91,0.44,0.98,0.08,0.79,0.33,0.00
453,0.77,0.80,0.96,0.82,0.66,0.00,0.32
85,0.33,0.87,0.65,0.49,0.76,0.00,1.00
583,0.86,0.80,0.15,0.03,0.24,0.00,1.00
176,0.16,0.75,0.74,0.34,0.34,0.33,0.00
295,0.14,0.00,0.08,0.81,0.31,1.00,0.00
813,0.37,0.76,0.17,0.15,0.24,0.33,1.00
991,0.33,0.62,0.74,0.88,0.72,0.67,1.00
46,0.58,0.31,0.03,0.52,0.31,0.00,0.00
19,1.00,0.07,0.39,0.48,0.62,0.67,0.32
426,0.65,0.34,0.84,0.23,0.66,0.33,0.00
980,0.56,0.46,0.14,0.04,0.79,1.00,1.00
384,0.95,0.22,0.18,0.09,0.79,0.33,0.32
259,0.72,0.24,0.60,0.82,1.00,0.67,0.00
796,0.49,0.22,0.50,0.34,0.48,1.00,0.32
58,0.07,0.35,0.87,0.94,0.90,0.67,0.00
47,0.02,0.80,0.85,0.49,0.17,1.00,0.00
536,0.26,0.45,0.52,0.98,0.03,1.00,0.32
430,0.35,0.90,0.89,0.19,0.59,0.00,0.32
984,0.88,0.22,0.31,0.40,0.07,0.67,0.32
100,0.74,0.08,0.84,0.85,0.07,0.67,0.00
691,0.79,1.00,0.31,0.95,0.14,0.00,1.00
166,0.56,0.50,0.26,0.66,0.03,0.33,1.00
509,0.84,0.22,0.74,0.59,1.00,0.00,1.00
400,0.91,0.64,0.84,0.23,0.62,1.00,0.00
11,0.53,1.00,0.13,0.98,0.62,0.33,0.32
952,1.00,0.55,0.59,0.39,0.21,1.00,0.32
92,1.00,0.04,0.43,0.59,0.14,1.00,0.32
619,1.00,0.18,0.24,0.11,0.90,0.00,0.00
165,0.63,0.39,0.61,0.69,0.59,1.00,1.00
311,0.74,0.50,0.21,0.22,0.72,0.33,0.00
358,0.65,0.18,0.85,0.16,0.21,0.33,0.32
291,0.30,0.18,0.22,0.70,0.31,0.33,0.32
802,0.26,0.75,0.44,0.79,0.79,0.33,1.00
914,0.74,0.01,0.10,0.68,0.41,0.33,0.32
637,0.35,0.34,0.63,0.50,0.66,0.33,0.32
74,0.30,0.00,0.83,0.74,0.34,0.67,0.32
468,0.44,0.07,0.69,0.97,0.79,0.00,1.00
744,0.77,0.93,0.94,0.99,0.59,0.33,0.00
247,0.70,0.64,0.36,0.92,0.21,0.00,0.00
163,0.67,0.14,0.36,0.51,0.48,0.67,0.32
123,0.84,0.80,0.85,0.55,0.76,0.33,0.00
152,0.14,0.52,0.50,0.74,0.34,0.00,0.32
5,0.47,0.52,0.96,0.49,0.90,1.00,0.32
202,0.00,0.18,0.46,0.55,0.07,0.67,0.32
320,0.63,0.52,0.64,0.20,0.48,1.00,1.00
399,0.79,0.72,0.69,0.58,0.62,0.00,0.00
27,1.00,1.00,0.02,0.66,1.00,1.00,1.00
900,0.67,0.35,0.29,0.82,1.00,0.00,0.00
122,0.79,0.46,0.39,0.59,0.00,0.00,0.00
935,0.28,0.42,0.02,0.12,0.69,0.00,0.32
97,0.16,0.76,0.18,0.72,0.34,1.00,0.00
620,0.72,0.80,0.84,0.35,0.66,1.00,0.32
116,1.00,0.07,0.09,0.11,0.41,0.33,1.00
50,0.14,0.50,0.34,0.45,0.55,0.33,1.00
559,0.70,0.34,0.22,0.59,0.86,0.00,1.00
285,0.35,0.34,0.88,0.59,0.72,0.00,0.32
847,1.00,0.42,0.35,0.87,0.66,1.00,1.00
35,0.05,0.46,0.46,0.34,0.21,1.00,1.00
792,0.09,0.01,0.11,0.67,0.21,1.00,0.32
942,0.37,0.22,0.36,0.03,0.17,0.33,1.00
974,0.42,0.76,0.65,0.70,0.24,1.00,1.00
737,0.30,0.14,0.31,0.63,0.48,0.67,1.00
402,0.28,0.55,0.33,0.37,0.28,0.67,1.00
686,0.60,0.72,0.96,0.43,0.03,1.00,1.00
26,0.49,0.39,0.35,0.82,0.03,0.00,0.00
706,0.21,0.35,0.93,0.23,0.97,1.00,1.00
976,0.58,0.02,0.25,0.63,0.41,1.00,0.32
827,0.02,0.64,0.84,0.20,1.00,0.00,0.32
277,0.56,0.68,0.99,0.37,0.69,1.00,0.00
635,0.00,0.44,0.97,0.26,0.55,0.67,1.00
179,0.84,0.08,0.62,0.62,0.10,1.00,0.00
354,0.74,0.14,0.42,0.52,0.14,0.33,0.32
283,0.02,0.01,0.69,0.23,1.00,1.00,0.00
811,0.67,0.93,0.30,0.65,0.76,0.67,0.32
272,0.81,0.14,0.63,0.01,0.76,0.00,1.00
454,0.70,0.45,0.03,0.86,0.34,0.33,1.00
544,0.70,0.80,0.59,0.38,0.55,1.00,1.00
189,0.26,0.62,0.63,0.72,0.00,0.00,1.00
161,1.00,0.19,0.73,0.39,0.34,0.33,1.00
579,0.02,0.04,0.69,0.72,0.66,0.33,0.32
556,0.95,0.97,0.51,0.50,0.41,0.00,0.00
985,0.91,0.39,0.04,0.90,0.93,0.00,0.32
711,0.19,0.75,0.17,0.45,0.59,0.00,0.32
869,0.58,0.76,0.60,0.76,0.55,1.00,0.32
511,0.53,0.18,0.16,0.25,0.38,1.00,1.00
102,0.95,0.50,0.91,0.48,0.86,1.00,0.00
300,0.49,0.46,0.09,0.81,0.03,0.33,1.00
389,0.74,0.55,0.16,0.27,0.52,1.00,1.00
721,0.16,0.04,0.62,0.34,0.83,0.67,0.00
757,0.09,0.31,0.75,0.10,0.07,0.67,0.00
86,0.00,0.02,0.95,0.28,0.48,0.33,0.32
734,0.33,0.46,0.97,0.58,0.72,1.00,1.00
498,0.77,0.08,0.10,0.64,0.55,0.33,0.32
395,0.07,0.76,0.18,0.21,0.28,0.33,1.00
129,0.30,0.80,0.08,0.88,0.45,1.00,1.00
763,0.37,0.08,0.21,0.19,0.41,1.00,1.00
924,0.28,0.50,0.20,0.84,0.48,1.00,0.00
317,0.79,0.08,0.23,0.11,0.34,0.00,0.00
598,0.60,0.34,0.09,0.77,0.17,0.67,0.32
975,0.30,0.50,0.44,0.18,0.83,0.67,0.00
219,0.23,0.97,0.12,0.07,0.69,0.33,0.32
687,0.28,0.24,0.42,0.29,0.76,0.00,0.32
304,0.86,0.51,0.91,0.44,0.34,0.67,0.32
42,0.07,0.18,0.76,0.13,0.10,0.67,0.00
328,0.65,0.22,0.45,0.69,0.48,1.00,1.00
528,0.67,0.97,0.55,0.95,0.38,1.00,1.00
713,0.28,0.02,0.29,0.26,0.76,1.00,0.00
531,0.56,0.46,0.56,0.97,0.34,0.00,1.00
850,0.28,0.64,0.68,0.79,1.00,0.00,1.00
776,0.70,0.87,0.08,0.28,0.34,0.00,1.00
462,0.53,0.18,0.34,0.39,0.55,1.00,0.32
741,0.86,0.08,0.07,0.48,0.45,0.33,0.32
605,0.63,0.22,0.10,0.02,0.97,0.67,1.00
198,0.51,0.01,1.00,0.20,0.93,1.00,0.32
966,0.93,0.62,0.47,0.59,0.83,1.00,0.00
9,0.23,0.34,0.43,0.92,0.10,0.67,0.32
408,0.63,0.01,0.89,0.30,0.45,0.00,1.00
284,0.79,0.42,0.57,0.72,0.72,0.33,0.32
571,0.37,0.46,0.95,0.57,0.10,0.00,0.32
383,0.49,0.35,0.90,0.30,0.79,0.00,1.00
624,0.23,0.01,0.89,0.75,0.90,0.67,0.32
921,0.84,0.07,0.41,0.32,0.55,0.00,1.00
562,0.51,0.75,0.85,0.89,0.90,0.33,0.00
530,0.44,0.31,0.64,0.78,0.38,0.33,0.32
983,0.16,0.24,0.00,0.54,1.00,0.00,0.32
249,0.95,0.02,0.94,0.50,0.28,0.33,0.00
610,0.88,0.87,0.27,0.56,0.59,0.33,0.32
702,0.51,0.52,0.38,0.56,0.83,0.00,0.32
642,0.72,0.01,0.58,0.36,0.72,0.67,0.00
590,0.56,0.34,0.45,0.34,0.07,0.33,0.00
72,0.33,0.34,0.90,0.46,0.93,0.33,0.00
334,0.51,0.64,0.16,0.62,0.62,0.67,0.00
82,0.56,0.76,0.00,0.92,0.21,0.33,1.00
136,0.95,0.55,0.79,0.77,0.83,0.67,1.00
371,0.30,0.04,0.71,0.27,0.07,0.67,0.00
809,0.58,0.55,0.97,0.93,0.55,1.00,0.00
957,0.26,0.62,0.15,0.05,0.24,1.00,0.32
618,0.12,0.97,0.69,0.39,0.52,1.00,0.00
312,0.63,0.90,0.71,0.06,0.48,0.33,0.32
305,0.16,0.24,0.78,0.99,0.45,0.00,0.32

In [275]:
from sklearn.linear_model import LogisticRegression

In [276]:
lr=LogisticRegression()

In [277]:
lr.fit(X_train, y_train.values.ravel())

LogisticRegression()

In [278]:
lr.score(X_test, y_test)

0.862

In [279]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [280]:
y_pred=lr.predict(X_test)

In [281]:
print('P_score', precision_score(y_test, y_pred))

P_score 0.0

C:\Users\gopal\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [282]:
macro_precision = precision_score(y_test, y_pred, average='macro', zero_division=0)

In [283]:
macro_precision

0.431

In [284]:
print('R_score', recall_score(y_test, y_pred))

R_score 0.0

In [285]:
print(confusion_matrix(y_test, y_pred))

[[431   0]
 [ 69   0]]

In [286]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.86      1.00      0.93       431
         1.0       0.00      0.00      0.00        69

    accuracy                           0.86       500
   macro avg       0.43      0.50      0.46       500
weighted avg       0.74      0.86      0.80       500

C:\Users\gopal\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\gopal\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\gopal\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])